name: lender_settings
primary_source_table: staging.staging_octane.lender_settings
primary_key:
- lss_pid
- lss_version
foreign_keys:
  fk_lender_settings_1:
    columns:
    - lss_account_pid
    references:
      columns:
      - a_pid
      schema: history_octane
      table: account
  fk_lender_settings_3:
    columns:
    - lss_hmda_contact_pid
    references:
      columns:
      - lu_pid
      schema: history_octane
      table: lender_user
  fk_lender_settings_4:
    columns:
    - lss_default_standalone_lock_term_setting_pid
    references:
      columns:
      - lts_pid
      schema: history_octane
      table: lock_term_setting
  fk_lender_settings_5:
    columns:
    - lss_default_combo_lock_term_setting_pid
    references:
      columns:
      - lts_pid
      schema: history_octane
      table: lock_term_setting
  fkt_lss_borrower_quote_filter_pivot_type:
    columns:
    - lss_borrower_quote_filter_pivot_type
    references:
      columns:
      - code
      schema: history_octane
      table: quote_filter_pivot_type
  fkt_lss_company_time_zone_type:
    columns:
    - lss_company_time_zone_type
    references:
      columns:
      - code
      schema: history_octane
      table: time_zone_type
  fkt_lss_default_credit_bureau_type:
    columns:
    - lss_default_credit_bureau_type
    references:
      columns:
      - code
      schema: history_octane
      table: credit_bureau_type
  fkt_lss_hmda_agency_id_type:
    columns:
    - lss_hmda_agency_id_type
    references:
      columns:
      - code
      schema: history_octane
      table: hmda_agency_id_type
  fkt_lss_lp_submission_type:
    columns:
    - lss_lp_submission_type
    references:
      columns:
      - code
      schema: history_octane
      table: lp_submission_type
  fkt_lss_preferred_aus_type:
    columns:
    - lss_preferred_aus_type
    references:
      columns:
      - code
      schema: history_octane
      table: aus_type
columns:
  data_source_deleted_flag:
    data_type: BOOLEAN
  data_source_updated_datetime:
    data_type: TIMESTAMPTZ
  etl_batch_id:
    data_type: TEXT
  lss_account_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.lss_account_pid
  lss_borrower_quote_filter_pivot_higher_count:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.lss_borrower_quote_filter_pivot_higher_count
  lss_borrower_quote_filter_pivot_lower_count:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.lss_borrower_quote_filter_pivot_lower_count
  lss_borrower_quote_filter_pivot_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_borrower_quote_filter_pivot_type
  lss_company_time_zone_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_company_time_zone_type
  lss_default_combo_lock_term_setting_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.lss_default_combo_lock_term_setting_pid
  lss_default_credit_bureau_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_default_credit_bureau_type
  lss_default_standalone_lock_term_setting_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.lss_default_standalone_lock_term_setting_pid
  lss_equifax_submitting_party_name:
    data_type: VARCHAR(256)
    source:
      field: primary_source_table.columns.lss_equifax_submitting_party_name
  lss_factual_data_submitting_party_id:
    data_type: VARCHAR(256)
    source:
      field: primary_source_table.columns.lss_factual_data_submitting_party_id
  lss_factual_data_submitting_party_name:
    data_type: VARCHAR(256)
    source:
      field: primary_source_table.columns.lss_factual_data_submitting_party_name
  lss_fha_home_office_branch_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.lss_fha_home_office_branch_pid
  lss_fha_home_office_location_pid:
    data_type: BIGINT
  lss_fha_lender_id:
    data_type: VARCHAR(16)
  lss_fha_non_supervised_mortgagee:
    data_type: BOOLEAN
  lss_fha_sponsor_address_city:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_country:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_postal_code:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_state:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_street1:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_street2:
    data_type: VARCHAR(128)
  lss_fha_sponsor_company_name:
    data_type: VARCHAR(32)
  lss_fha_sponsor_id:
    data_type: VARCHAR(16)
  lss_fnma_seller_id:
    data_type: VARCHAR(16)
    source:
      field: primary_source_table.columns.lss_fnma_seller_id
  lss_fre_seller_id:
    data_type: VARCHAR(16)
    source:
      field: primary_source_table.columns.lss_fre_seller_id
  lss_hmda_agency_id_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_hmda_agency_id_type
  lss_hmda_contact_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.lss_hmda_contact_pid
  lss_hmda_legal_entity_id:
    data_type: VARCHAR(20)
    source:
      field: primary_source_table.columns.lss_hmda_legal_entity_id
  lss_hmda_respondent_id:
    data_type: VARCHAR(32)
    source:
      field: primary_source_table.columns.lss_hmda_respondent_id
  lss_lender_user_email_from:
    data_type: VARCHAR(256)
    source:
      field: primary_source_table.columns.lss_lender_user_email_from
  lss_lp_submission_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_lp_submission_type
  lss_meridian_link_submitting_party_id:
    data_type: VARCHAR(256)
    source:
      field: primary_source_table.columns.lss_meridian_link_submitting_party_id
  lss_originator_title:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_originator_title
  lss_pest_inspector_address_city:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_pest_inspector_address_city
  lss_pest_inspector_address_postal_code:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_pest_inspector_address_postal_code
  lss_pest_inspector_address_state:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_pest_inspector_address_state
  lss_pest_inspector_address_street1:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_pest_inspector_address_street1
  lss_pest_inspector_address_street2:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_pest_inspector_address_street2
  lss_pest_inspector_company_name:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_pest_inspector_company_name
  lss_pest_inspector_phone:
    data_type: VARCHAR(32)
    source:
      field: primary_source_table.columns.lss_pest_inspector_phone
  lss_pest_inspector_website_url:
    data_type: VARCHAR(256)
    source:
      field: primary_source_table.columns.lss_pest_inspector_website_url
  lss_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.lss_pid
  lss_preapproval_program:
    data_type: BOOLEAN
    source:
      field: primary_source_table.columns.lss_preapproval_program
  lss_preferred_aus_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_preferred_aus_type
  lss_prequalification_program:
    data_type: BOOLEAN
    source:
      field: primary_source_table.columns.lss_prequalification_program
  lss_sap_minimum_decision_credit_score:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.lss_sap_minimum_decision_credit_score
  lss_take_application_hours:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.lss_take_application_hours
  lss_usda_lender_id:
    data_type: VARCHAR(16)
  lss_va_lender_id:
    data_type: VARCHAR(16)
  lss_version:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.lss_version
step_functions:
  SP-100095:
    etls:
      ETL-100095:
        input_type: table
        output_type: insert
        output_table: staging.history_octane.lender_settings
        json_output_field: lss_pid
        truncate_table: false
        container_memory: 2048
        input_sql: |-
          --finding records to insert into history_octane.lender_settings
          SELECT staging_table.lss_pid
               , staging_table.lss_version
               , staging_table.lss_account_pid
               , staging_table.lss_company_time_zone_type
               , staging_table.lss_fha_home_office_branch_pid
               , staging_table.lss_fnma_seller_id
               , staging_table.lss_fre_seller_id
               , staging_table.lss_lp_submission_type
               , staging_table.lss_lender_user_email_from
               , staging_table.lss_hmda_contact_pid
               , staging_table.lss_hmda_legal_entity_id
               , staging_table.lss_hmda_respondent_id
               , staging_table.lss_hmda_agency_id_type
               , staging_table.lss_prequalification_program
               , staging_table.lss_preapproval_program
               , staging_table.lss_pest_inspector_company_name
               , staging_table.lss_pest_inspector_phone
               , staging_table.lss_pest_inspector_website_url
               , staging_table.lss_pest_inspector_address_street1
               , staging_table.lss_pest_inspector_address_street2
               , staging_table.lss_pest_inspector_address_city
               , staging_table.lss_pest_inspector_address_state
               , staging_table.lss_pest_inspector_address_postal_code
               , staging_table.lss_take_application_hours
               , staging_table.lss_originator_title
               , staging_table.lss_default_credit_bureau_type
               , staging_table.lss_sap_minimum_decision_credit_score
               , staging_table.lss_default_standalone_lock_term_setting_pid
               , staging_table.lss_default_combo_lock_term_setting_pid
               , staging_table.lss_preferred_aus_type
               , staging_table.lss_borrower_quote_filter_pivot_type
               , staging_table.lss_borrower_quote_filter_pivot_lower_count
               , staging_table.lss_borrower_quote_filter_pivot_higher_count
               , staging_table.lss_equifax_submitting_party_name
               , staging_table.lss_factual_data_submitting_party_name
               , staging_table.lss_factual_data_submitting_party_id
               , staging_table.lss_meridian_link_submitting_party_id
               , FALSE AS data_source_deleted_flag
               , NOW( ) AS data_source_updated_datetime
          FROM staging_octane.lender_settings staging_table
          LEFT JOIN history_octane.lender_settings history_table
                    ON staging_table.lss_pid = history_table.lss_pid
                        AND staging_table.lss_version = history_table.lss_version
          WHERE history_table.lss_pid IS NULL
          UNION ALL
          SELECT history_table.lss_pid
               , history_table.lss_version + 1
               , history_table.lss_account_pid
               , history_table.lss_company_time_zone_type
               , history_table.lss_fha_home_office_branch_pid
               , history_table.lss_fnma_seller_id
               , history_table.lss_fre_seller_id
               , history_table.lss_lp_submission_type
               , history_table.lss_lender_user_email_from
               , history_table.lss_hmda_contact_pid
               , history_table.lss_hmda_legal_entity_id
               , history_table.lss_hmda_respondent_id
               , history_table.lss_hmda_agency_id_type
               , history_table.lss_prequalification_program
               , history_table.lss_preapproval_program
               , history_table.lss_pest_inspector_company_name
               , history_table.lss_pest_inspector_phone
               , history_table.lss_pest_inspector_website_url
               , history_table.lss_pest_inspector_address_street1
               , history_table.lss_pest_inspector_address_street2
               , history_table.lss_pest_inspector_address_city
               , history_table.lss_pest_inspector_address_state
               , history_table.lss_pest_inspector_address_postal_code
               , history_table.lss_take_application_hours
               , history_table.lss_originator_title
               , history_table.lss_default_credit_bureau_type
               , history_table.lss_sap_minimum_decision_credit_score
               , history_table.lss_default_standalone_lock_term_setting_pid
               , history_table.lss_default_combo_lock_term_setting_pid
               , history_table.lss_preferred_aus_type
               , history_table.lss_borrower_quote_filter_pivot_type
               , history_table.lss_borrower_quote_filter_pivot_lower_count
               , history_table.lss_borrower_quote_filter_pivot_higher_count
               , history_table.lss_equifax_submitting_party_name
               , history_table.lss_factual_data_submitting_party_name
               , history_table.lss_factual_data_submitting_party_id
               , history_table.lss_meridian_link_submitting_party_id
               , TRUE AS data_source_deleted_flag
               , NOW( ) AS data_source_updated_datetime
          FROM history_octane.lender_settings history_table
          LEFT JOIN staging_octane.lender_settings staging_table
                    ON staging_table.lss_pid = history_table.lss_pid
          WHERE staging_table.lss_pid IS NULL
            AND NOT EXISTS(
              SELECT 1
              FROM history_octane.lender_settings deleted_records
              WHERE deleted_records.lss_pid = history_table.lss_pid
                AND deleted_records.data_source_deleted_flag = TRUE
              );
