name: role_config_export_permission
primary_source_table: staging.staging_octane.role_config_export_permission
primary_key:
- rcep_pid
- rcep_version
foreign_keys:
  fk_role_config_export_permission_1:
    columns:
    - rcep_role_pid
    references:
      columns:
      - r_pid
      schema: history_octane
      table: role
  fkt_rcep_export_permission_type:
    columns:
    - rcep_config_export_permission_type
    references:
      columns:
      - code
      schema: history_octane
      table: config_export_permission_type
columns:
  data_source_deleted_flag:
    data_type: BOOLEAN
  data_source_updated_datetime:
    data_type: TIMESTAMPTZ
  etl_batch_id:
    data_type: TEXT
  rcep_config_export_permission_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.rcep_config_export_permission_type
  rcep_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.rcep_pid
  rcep_role_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.rcep_role_pid
  rcep_version:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.rcep_version
etls:
  SP-100234:
    input_type: table
    output_type: insert
    json_output_field: rcep_pid
    truncate_table: false
    input_sql: |-
      --finding records to insert into history_octane.role_config_export_permission
      SELECT staging_table.rcep_pid
           , staging_table.rcep_version
           , staging_table.rcep_role_pid
           , staging_table.rcep_config_export_permission_type
           , FALSE AS data_source_deleted_flag
           , NOW( ) AS data_source_updated_datetime
      FROM staging_octane.role_config_export_permission staging_table
      LEFT JOIN history_octane.role_config_export_permission history_table
                ON staging_table.rcep_pid = history_table.rcep_pid
                    AND staging_table.rcep_version = history_table.rcep_version
      WHERE history_table.rcep_pid IS NULL
      UNION ALL
      SELECT history_table.rcep_pid
           , history_table.rcep_version + 1
           , history_table.rcep_role_pid
           , history_table.rcep_config_export_permission_type
           , TRUE AS data_source_deleted_flag
           , NOW( ) AS data_source_updated_datetime
      FROM history_octane.role_config_export_permission history_table
      LEFT JOIN staging_octane.role_config_export_permission staging_table
                ON staging_table.rcep_pid = history_table.rcep_pid
      WHERE staging_table.rcep_pid IS NULL
        AND NOT EXISTS(
          SELECT 1
          FROM history_octane.role_config_export_permission deleted_records
          WHERE deleted_records.rcep_pid = history_table.rcep_pid
            AND deleted_records.data_source_deleted_flag = TRUE
          );
