name: password_settings
primary_source_table: staging.staging_octane.password_settings
primary_key:
- pws_pid
- pws_version
foreign_keys:
  fk_password_settings_1:
    columns:
    - pws_account_pid
    references:
      columns:
      - a_pid
      schema: history_octane
      table: account
columns:
  pws_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.pws_pid
  pws_version:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.pws_version
  pws_account_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.pws_account_pid
  pws_lender_user_expire_days:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.pws_lender_user_expire_days
  pws_lender_user_minimum_change_days:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.pws_lender_user_minimum_change_days
  pws_lender_user_previous_password_ban:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.pws_lender_user_previous_password_ban
  pws_minimum_length:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.pws_minimum_length
  pws_require_special_character:
    data_type: BOOLEAN
    source:
      field: primary_source_table.columns.pws_require_special_character
  pws_require_uppercase_letter:
    data_type: BOOLEAN
    source:
      field: primary_source_table.columns.pws_require_uppercase_letter
  pws_require_lowercase_letter:
    data_type: BOOLEAN
    source:
      field: primary_source_table.columns.pws_require_lowercase_letter
  pws_require_digit:
    data_type: BOOLEAN
    source:
      field: primary_source_table.columns.pws_require_digit
  data_source_updated_datetime:
    data_type: TIMESTAMPTZ
  data_source_deleted_flag:
    data_type: BOOLEAN
etls:
  SP-100869:
    input_type: table
    output_type: insert
    json_output_field: pws_pid
    truncate_table: false
    input_sql: |-
      --finding records to insert into history_octane.password_settings
      SELECT staging_table.pws_pid
           , staging_table.pws_version
           , staging_table.pws_account_pid
           , staging_table.pws_lender_user_expire_days
           , staging_table.pws_lender_user_minimum_change_days
           , staging_table.pws_lender_user_previous_password_ban
           , staging_table.pws_minimum_length
           , staging_table.pws_require_special_character
           , staging_table.pws_require_uppercase_letter
           , staging_table.pws_require_lowercase_letter
           , staging_table.pws_require_digit
           , FALSE AS data_source_deleted_flag
           , NOW( ) AS data_source_updated_datetime
      FROM staging_octane.password_settings staging_table
      LEFT JOIN history_octane.password_settings history_table
                ON staging_table.pws_pid = history_table.pws_pid
                    AND staging_table.pws_version = history_table.pws_version
      WHERE history_table.pws_pid IS NULL
      UNION ALL
      SELECT history_table.pws_pid
           , history_table.pws_version + 1
           , history_table.pws_account_pid
           , history_table.pws_lender_user_expire_days
           , history_table.pws_lender_user_minimum_change_days
           , history_table.pws_lender_user_previous_password_ban
           , history_table.pws_minimum_length
           , history_table.pws_require_special_character
           , history_table.pws_require_uppercase_letter
           , history_table.pws_require_lowercase_letter
           , history_table.pws_require_digit
           , TRUE AS data_source_deleted_flag
           , NOW( ) AS data_source_updated_datetime
      FROM history_octane.password_settings history_table
      LEFT JOIN staging_octane.password_settings staging_table
                ON staging_table.pws_pid = history_table.pws_pid
      WHERE staging_table.pws_pid IS NULL
        AND NOT EXISTS(
          SELECT 1
          FROM history_octane.password_settings deleted_records
          WHERE deleted_records.pws_pid = history_table.pws_pid
            AND deleted_records.data_source_deleted_flag = TRUE
          );
