name: config_note
primary_source_table: staging.staging_octane.config_note
primary_key:
- cn_pid
- cn_version
foreign_keys:
  fk_config_note_1:
    columns:
    - cn_account_pid
    references:
      columns:
      - a_pid
      schema: history_octane
      table: account
  fk_config_note_2:
    columns:
    - cn_author_lender_user_pid
    references:
      columns:
      - lu_pid
      schema: history_octane
      table: lender_user
  fk_config_note_3:
    columns:
    - cn_location_pid
    references:
      columns:
      - loc_pid
      schema: history_octane
      table: location
  fk_config_note_4:
    columns:
    - cn_smart_doc_pid
    references:
      columns:
      - sd_pid
      schema: history_octane
      table: smart_doc
  fk_config_note_5:
    columns:
    - cn_wf_process_pid
    references:
      columns:
      - wpr_pid
      schema: history_octane
      table: wf_process
  fk_config_note_6:
    columns:
    - cn_wf_step_pid
    references:
      columns:
      - ws_pid
      schema: history_octane
      table: wf_step
  fkt_cn_config_note_scope_type:
    columns:
    - cn_config_note_scope_type
    references:
      columns:
      - code
      schema: history_octane
      table: config_note_scope_type
columns:
  cn_account_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_account_pid
  cn_author_lender_user_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_author_lender_user_pid
  cn_author_unparsed_name:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.cn_author_unparsed_name
  cn_config_note_scope_type:
    data_type: VARCHAR(128)
    source:
      field: primary_source_table.columns.cn_config_note_scope_type
  cn_content:
    data_type: VARCHAR(16000)
    source:
      field: primary_source_table.columns.cn_content
  cn_create_datetime:
    data_type: TIMESTAMP
    source:
      field: primary_source_table.columns.cn_create_datetime
  cn_location_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_location_pid
  cn_old_location_note_pid:
    data_type: BIGINT
  cn_old_smart_doc_note_pid:
    data_type: BIGINT
  cn_old_wf_process_note_pid:
    data_type: BIGINT
  cn_old_wf_step_note_pid:
    data_type: BIGINT
  cn_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_pid
  cn_scope_name:
    data_type: VARCHAR(1024)
    source:
      field: primary_source_table.columns.cn_scope_name
  cn_smart_doc_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_smart_doc_pid
  cn_version:
    data_type: INTEGER
    source:
      field: primary_source_table.columns.cn_version
  cn_wf_process_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_wf_process_pid
  cn_wf_step_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.cn_wf_step_pid
  data_source_deleted_flag:
    data_type: BOOLEAN
  data_source_updated_datetime:
    data_type: TIMESTAMPTZ
  etl_batch_id:
    data_type: TEXT
step_functions:
  SP-100901:
    etls:
      ETL-100901:
        input_type: table
        output_type: insert
        output_table: staging.history_octane.config_note
        json_output_field: cn_pid
        truncate_table: false
        container_memory: 2048
        input_sql: |-
          --finding records to insert into history_octane.config_note
          SELECT staging_table.cn_pid
               , staging_table.cn_version
               , staging_table.cn_account_pid
               , staging_table.cn_create_datetime
               , staging_table.cn_content
               , staging_table.cn_author_unparsed_name
               , staging_table.cn_author_lender_user_pid
               , staging_table.cn_config_note_scope_type
               , staging_table.cn_scope_name
               , staging_table.cn_location_pid
               , staging_table.cn_smart_doc_pid
               , staging_table.cn_wf_process_pid
               , staging_table.cn_wf_step_pid
               , FALSE AS data_source_deleted_flag
               , NOW( ) AS data_source_updated_datetime
          FROM staging_octane.config_note staging_table
          LEFT JOIN history_octane.config_note history_table
                    ON staging_table.cn_pid = history_table.cn_pid
                        AND staging_table.cn_version = history_table.cn_version
          WHERE history_table.cn_pid IS NULL
          UNION ALL
          SELECT history_table.cn_pid
               , history_table.cn_version + 1
               , history_table.cn_account_pid
               , history_table.cn_create_datetime
               , history_table.cn_content
               , history_table.cn_author_unparsed_name
               , history_table.cn_author_lender_user_pid
               , history_table.cn_config_note_scope_type
               , history_table.cn_scope_name
               , history_table.cn_location_pid
               , history_table.cn_smart_doc_pid
               , history_table.cn_wf_process_pid
               , history_table.cn_wf_step_pid
               , TRUE AS data_source_deleted_flag
               , NOW( ) AS data_source_updated_datetime
          FROM (
              SELECT current_records.*
              FROM history_octane.config_note AS current_records
              LEFT JOIN history_octane.config_note AS history_records
                        ON current_records.cn_pid = history_records.cn_pid
                            AND current_records.data_source_updated_datetime < history_records.data_source_updated_datetime
              WHERE history_records.data_source_updated_datetime IS NULL
                AND current_records.data_source_deleted_flag = FALSE
          ) AS history_table
          LEFT JOIN staging_octane.config_note staging_table
                    ON staging_table.cn_pid = history_table.cn_pid
          WHERE staging_table.cn_pid IS NULL;
