
----------------------------------------
-- This script is an addendum to the full script generated by staging_history_metadata_creater.sql
-- This will update the source_edw_field_definition_dwid in the history_octane field definitions.
--
-- WARNING: This is designed to work when there are no other joins declared from the tables other than the join from
-- staging_octane to history_octane.
----------------------------------------

update mdi.edw_field_definition
SET source_edw_field_definition_dwid  = staging_field_table.dwid
FROM mdi.edw_join_definition
         join (select dwid, field_name, edw_table_definition_dwid from mdi.edw_field_definition) as staging_field_table
              on edw_join_definition.target_edw_table_definition_dwid = staging_field_table.edw_table_definition_dwid
where edw_field_definition.source_edw_join_definition_dwid = edw_join_definition.dwid
  and staging_field_table.field_name = edw_field_definition.field_name
;