GRANT SELECT ON ALL TABLES IN SCHEMA flyway TO readonly;

GRANT USAGE ON SCHEMA loan TO readonly;
GRANT USAGE ON SCHEMA loan TO encompass_sp6;
GRANT SELECT ON ALL TABLES IN SCHEMA loan TO readonly;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA loan TO encompass_sp6;

GRANT USAGE ON SCHEMA star_common TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA star_common TO readonly;

