--
-- EDW | permissions - clean up non-star_loan user permissions
-- https://app.asana.com/0/0/1200548116207040
--

GRANT SELECT ON ALL TABLES IN SCHEMA flyway TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE deployer IN SCHEMA flyway GRANT SELECT ON TABLES TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA "flyway-permissions" TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE deployer IN SCHEMA "flyway-permissions" GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA history_octane REVOKE SELECT ON TABLES FROM readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA loan TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE deployer IN SCHEMA loan GRANT SELECT ON TABLES TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA octane_data_mart TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE deployer IN SCHEMA octane_data_mart GRANT SELECT ON TABLES TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA staging_compliance TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE deployer IN SCHEMA staging_compliance GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA star_loan REVOKE SELECT ON TABLES FROM readonly;

GRANT SELECT ON ALL TABLES IN SCHEMA octane_data_mart TO svc_octane;
ALTER DEFAULT PRIVILEGES FOR ROLE deployer IN SCHEMA octane_data_mart GRANT SELECT ON TABLES TO svc_octane;
