version: '3.8'
services:
    flyway-ingress:
        image: ${FLYWAY_IMAGE:-flyway/flyway:6}
        command: -url=jdbc:postgresql://database:5432/ingress -schemas=flyway-permissions -user=admin -password=testonly -connectRetries=60 migrate
        volumes:
            - ./database/migrations/ingress-permissions:/flyway/sql
        networks:
            - edw_default
    flyway-staging:
        image: ${FLYWAY_IMAGE:-flyway/flyway:6}
        command: -url=jdbc:postgresql://database:5432/staging -schemas=flyway-permissions -user=admin -password=testonly -connectRetries=60 migrate
        volumes:
            - ./database/migrations/staging-permissions:/flyway/sql
        networks:
            - edw_default
    flyway-config:
        image: ${FLYWAY_IMAGE:-flyway/flyway:6}
        command: -url=jdbc:postgresql://database:5432/config -schemas=flyway-permissions -user=admin -password=testonly -connectRetries=60 migrate
        volumes:
            - ./database/migrations/config-permissions:/flyway/sql
        networks:
            - edw_default
networks:
    edw_default:
        external: true
