version: '3.8'
services:
  database:
    # we build the image so we may copy an init script in.
    # trying to copy the init script as a volume leads to errors reading it.  this works.
    image: ${POSTGRES_IMAGE:-postgres:12}
    environment:
      - POSTGRES_PASSWORD=testonly
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    shm_size: 2gb
  flyway-roles:
    # this creates users/roles, etc that are normally created in terraform
    image: ${FLYWAY_IMAGE:-flyway/flyway:8}
    command: -url=jdbc:postgresql://database:5432/postgres -schemas=flyway-baseline -user=postgres -password=testonly -connectRetries=60 migrate
    volumes:
      - ./database/baseline/roles:/flyway/sql
    depends_on:
      - database
