version: '3.8'
services:
    flyway-ingress:
        image: flyway/flyway:8
        command: -url=jdbc:postgresql://database:5432/ingress -schemas=flyway-baseline -user=postgres -password=testonly -connectRetries=60 migrate
        volumes:
            - ./database/baseline/ingress:/flyway/sql
        networks:
            - edw_default
    flyway-staging:
        image: flyway/flyway:8
        command: -url=jdbc:postgresql://database:5432/staging -schemas=flyway-baseline -user=postgres -password=testonly -connectRetries=60 migrate
        volumes:
            - ./database/baseline/staging:/flyway/sql
        networks:
            - edw_default
    flyway-config:
        image: flyway/flyway:8
        command: -url=jdbc:postgresql://database:5432/config -schemas=flyway-baseline -user=postgres -password=testonly -connectRetries=60 migrate
        volumes:
            - ./database/baseline/config:/flyway/sql
        networks:
            - edw_default
networks:
    edw_default:
        external: true
