--
-- Main | EDW - Octane schemas from prod-release to v2021.10.4.2 on uat (PATCH to include loan_hedge changes from Octane 2021.10.3.6
-- https://app.asana.com/0/0/1201270648418743
--

WITH new_fields (table_name, field_name, field_order) AS (
    VALUES ('loan_hedge', 'lh_charges_enabled_date', 301)
    , ('loan_hedge', 'lh_application_date', 302)
)

, new_staging_field_definitions AS (
    INSERT INTO mdi.edw_field_definition (edw_table_definition_dwid, field_name, key_field_flag)
        SELECT edw_table_definition.dwid
             , new_fields.field_name
             , FALSE
        FROM new_fields
            JOIN mdi.edw_table_definition ON edw_table_definition.schema_name = 'staging_octane'
                AND new_fields.table_name = edw_table_definition.table_name
        RETURNING dwid, edw_table_definition_dwid, field_name
)

, new_history_field_definitions AS (
    INSERT INTO mdi.edw_field_definition (edw_table_definition_dwid, field_name, key_field_flag, source_edw_field_definition_dwid)
        SELECT edw_table_definition.dwid
             , new_fields.field_name
             , FALSE
             , new_staging_field_definitions.dwid
        FROM new_fields
            JOIN mdi.edw_table_definition ON edw_table_definition.schema_name = 'history_octane'
                AND new_fields.table_name = edw_table_definition.table_name
            JOIN mdi.edw_table_definition AS source_table_definition ON source_table_definition.schema_name = 'staging_octane'
                AND source_table_definition.table_name = new_fields.table_name
            JOIN new_staging_field_definitions ON new_staging_field_definitions.edw_table_definition_dwid = source_table_definition.dwid
                AND new_staging_field_definitions.field_name = new_fields.field_name
)

, new_table_output_fields AS (
    INSERT INTO mdi.table_output_field (table_output_step_dwid, database_field_name, database_stream_name, field_order, is_sensitive)
        SELECT table_output_step.dwid
             , new_fields.field_name
             , new_fields.field_name
             , new_fields.field_order
             , FALSE
        FROM new_fields
            JOIN mdi.table_output_step ON table_output_step.target_schema = 'history_octane'
                AND table_output_step.target_table = new_fields.table_name
)

, updated_table_input_sql (table_name, sql) AS (
    VALUES ('loan_hedge', '--finding records to insert into history_octane.loan_hedge
SELECT staging_table.lh_pid
, staging_table.lh_version
, staging_table.lh_loan_pid
, staging_table.lh_update_datetime
, staging_table.lh_update_pending_datetime
, staging_table.lh_transaction_status_date
, staging_table.lh_loan_number
, staging_table.lh_product_code
, staging_table.lh_note_rate
, staging_table.lh_loan_amount
, staging_table.lh_lock_date
, staging_table.lh_buy_side_lock_expires_date
, staging_table.lh_lock_expiration_date
, staging_table.lh_secondary_cost
, staging_table.lh_total_cost_basis
, staging_table.lh_total_lender_margin
, staging_table.lh_stage
, staging_table.lh_fund_date
, staging_table.lh_allocation_date
, staging_table.lh_estimated_fund_date
, staging_table.lh_purchased_by_investor_date
, staging_table.lh_commitment_number
, staging_table.lh_property_occupancy
, staging_table.lh_property_type
, staging_table.lh_property_type_supplemental
, staging_table.lh_property_state
, staging_table.lh_property_zip
, staging_table.lh_property_number_of_units
, staging_table.lh_purchase_price
, staging_table.lh_appraised_value
, staging_table.lh_purpose
, staging_table.lh_refinance_type
, staging_table.lh_lien_position
, staging_table.lh_impounds
, staging_table.lh_buydown_type
, staging_table.lh_buydown
, staging_table.lh_ltv
, staging_table.lh_original_ltv
, staging_table.lh_cltv
, staging_table.lh_original_cltv
, staging_table.lh_effective_credit_score
, staging_table.lh_doc_type
, staging_table.lh_debt_to_income
, staging_table.lh_prepayment_penalty
, staging_table.lh_prepayment_penalty_term
, staging_table.lh_interest_only
, staging_table.lh_lock_type
, staging_table.lh_lock_period
, staging_table.lh_fees_collected_bps
, staging_table.lh_channel
, staging_table.lh_loan_officer
, staging_table.lh_branch
, staging_table.lh_broker
, staging_table.lh_correspondent
, staging_table.lh_origination_source
, staging_table.lh_investor
, staging_table.lh_investor_total_price
, staging_table.lh_investor_base_price
, staging_table.lh_investor_srp_paid
, staging_table.lh_investor_loan_number
, staging_table.lh_pmi
, staging_table.lh_pmi_percent
, staging_table.lh_mi_cert_number
, staging_table.lh_srp_paid
, staging_table.lh_discount_points
, staging_table.lh_date_docs_back
, staging_table.lh_note_date
, staging_table.lh_close_date
, staging_table.lh_first_payment_date
, staging_table.lh_last_payment_date
, staging_table.lh_next_scheduled_payment_due_date
, staging_table.lh_scheduled_principal_and_interest
, staging_table.lh_current_principal_and_interest
, staging_table.lh_minimum_principal_and_interest
, staging_table.lh_current_unpaid_principal_balance
, staging_table.lh_original_interest_rate
, staging_table.lh_maturity_date
, staging_table.lh_amortization_term
, staging_table.lh_yearly_payment_cap
, staging_table.lh_arm_margin
, staging_table.lh_arm_adjustment_date
, staging_table.lh_first_arm_period
, staging_table.lh_first_arm_adjustment_cap
, staging_table.lh_arm_life_floor
, staging_table.lh_arm_life_ceiling
, staging_table.lh_first_arm_payment_adjustment_date
, staging_table.lh_arm_period_after_first
, staging_table.lh_arm_adjustment_cap_after_first
, staging_table.lh_first_payment_cap
, staging_table.lh_payment_cap_option
, staging_table.lh_neg_am_flag
, staging_table.lh_maximum_negative_amortization
, staging_table.lh_arm_convertible
, staging_table.lh_arm_index
, staging_table.lh_dual_loan_flag
, staging_table.lh_other_loan_number
, staging_table.lh_agency_extract_fields
, staging_table.lh_warehouse_bank
, staging_table.lh_wire_amount
, staging_table.lh_credit_rating_agency_fields
, staging_table.lh_levels_fields
, staging_table.lh_data_fields
, staging_table.lh_loan_status
, staging_table.lh_suspense_yes_no
, staging_table.lh_loan_type
, staging_table.lh_hud_borr_paid_by_for_borr_other_amount
, staging_table.lh_fees_line_user_def_fee_one_borr
, staging_table.lh_uw_suspended_cleared_date
, staging_table.lh_underwriting_suspended_date
, staging_table.lh_line_orig_charge
, staging_table.lh_amortization_type
, staging_table.lh_milestone
, staging_table.lh_msa
, staging_table.lh_county_code
, staging_table.lh_ship_date_to_investor
, staging_table.lh_borrower_last_name
, staging_table.lh_purchase_advice_suspense_fee
, staging_table.lh_purchase_advice_early_delivery_amount
, staging_table.lh_purchase_advice_llpa
, staging_table.lh_purchase_advice_fmna
, staging_table.lh_purchase_advice_rp
, staging_table.lh_lock_info_relock_amount
, staging_table.lh_lock_info_loan_basis
, staging_table.lh_lock_info_lock_request_fulfilled_date_time
, staging_table.lh_lock_info_rate_lock_request_rate_sheet_id
, staging_table.lh_current_status_change_date
, staging_table.lh_aus_type
, staging_table.lh_buy_side_base_arm_margin
, staging_table.lh_uldd_poolid
, staging_table.lh_warehouse_co_name
, staging_table.lh_underwriting_investor_eligibility_wells_fargo
, staging_table.lh_underwriting_investor_eligibility_chase
, staging_table.lh_du_fail_reason
, staging_table.lh_lpmi_total_costs_on_lock
, staging_table.lh_lpmi_after_lock_required
, staging_table.lh_lpmi_after_lock_bps
, staging_table.lh_mi_company_name_type
, staging_table.lh_lpmi_frequency
, staging_table.lh_lpmi_estimated_amount_of_lender_paid_mi
, staging_table.lh_mortgage_insurance_premium_source_type
, staging_table.lh_loan_amount_repeat
, staging_table.lh_product_code_repeat
, staging_table.lh_note_rate_repeat
, staging_table.lh_loan_info_loan_id
, staging_table.lh_salable_loan
, staging_table.lh_sale_hold
, staging_table.lh_sale_hold_comments
, staging_table.lh_pf_disbursement_ledger_date
, staging_table.lh_aus_eligibility
, staging_table.lh_texas_cash_out
, staging_table.lh_acceptable_du
, staging_table.lh_acceptable_lp
, staging_table.lh_financed_property_count
, staging_table.lh_payoff_primary_lien_holder_company
, staging_table.lh_payoff_junior_lien_holder_company
, staging_table.lh_base_loan_amount
, staging_table.lh_funding_authorized
, staging_table.lh_credit_committee_fico_exception
, staging_table.lh_home_ready_eligibility
, staging_table.lh_home_ready_borr_acceptance
, staging_table.lh_home_ready_eligibility_review
, staging_table.lh_home_possible_eligibility
, staging_table.lh_home_possible_eligibility_review
, staging_table.lh_piw
, staging_table.lh_piw_fee
, staging_table.lh_uw_investor_eligibility_fnma
, staging_table.lh_uw_investor_eligibility_fhlmc
, staging_table.lh_appraisal_form
, staging_table.lh_ext_cos_total_amt
, staging_table.lh_fnmcu_risk_score
, staging_table.lh_borrower_income_verification
, staging_table.lh_co_borrower_income_verification
, staging_table.lh_day_one_income_verification_available
, staging_table.lh_subject_property_estimated_value
, staging_table.lh_transaction_status
, staging_table.lh_buy_status
, staging_table.lh_appraisal_exists
, staging_table.lh_du_piw_eligible
, staging_table.lh_lp_appraisal_waiver_eligible
, staging_table.lh_borrower_first_name
, staging_table.lh_co_borrower_first_name
, staging_table.lh_co_borrower_last_name
, staging_table.lh_total_borrower_income
, staging_table.lh_subject_property_city
, staging_table.lh_subject_property_county
, staging_table.lh_subject_property_zip
, staging_table.lh_borrower_decision_credit_score
, staging_table.lh_co_borrower_decision_credit_score
, staging_table.lh_underwriter_disposition
, staging_table.lh_underwrite_risk_assessment_type
, staging_table.lh_subject_property_address
, staging_table.lh_original_lock_date
, staging_table.lh_original_lock_period
, staging_table.lh_borrower_income_docs_required_count
, staging_table.lh_borrower_income_docs_fulfilled_count
, staging_table.lh_borrower_income_docs_approved_count
, staging_table.lh_borrower_asset_docs_required_count
, staging_table.lh_borrower_asset_docs_fulfilled_count
, staging_table.lh_borrower_asset_docs_approved_count
, staging_table.lh_borrower_credit_docs_required_count
, staging_table.lh_borrower_credit_docs_fulfilled_count
, staging_table.lh_borrower_credit_docs_approved_count
, staging_table.lh_initial_uw_submit_date_time
, staging_table.lh_cd_clear_date
, staging_table.lh_lender_concession_total_approved_amount
, staging_table.lh_relock_fee_gross_amount
, staging_table.lh_relock_fee_amount_less_concessions
, staging_table.lh_relock_fee_amount_concessed
, staging_table.lh_lock_extension_fee_gross_amount
, staging_table.lh_lock_extension_fee_amount_less_concessions
, staging_table.lh_lock_extension_fee_amount_concessed
, staging_table.lh_general_lender_concessions_amount_non_itemized
, staging_table.lh_day_one_concessions
, staging_table.lh_investor_lock_commitment_type
, staging_table.lh_signed_closing_doc_received_datetime
, staging_table.lh_geocoding_msa_code
, staging_table.lh_geocoding_state_code
, staging_table.lh_geocoding_county_code
, staging_table.lh_geocoding_census_tract
, staging_table.lh_tolerance_cure_amount
, staging_table.lh_self_employed_flag
, staging_table.lh_first_time_homebuyer
, staging_table.lh_mortgage_insurance_lpmi_rate_adjustment
, staging_table.lh_eligible_for_qm_status
, staging_table.lh_safe_harbor_test_passed
, staging_table.lh_hpml
, staging_table.lh_hoepa
, staging_table.lh_funding_status
, staging_table.lh_early_funding
, staging_table.lh_early_funding_date
, staging_table.lh_lqa_purchase_eligibility_type
, staging_table.lh_transferred_appraisal
, staging_table.lh_appraisal_cu_risk_score
, staging_table.lh_mi_upfront_rate
, staging_table.lh_loan_funding_requested_date
, staging_table.lh_student_loan_cash_out
, staging_table.lh_octane_high_balance
, staging_table.lh_borrower_final_price
, staging_table.lh_charge_credit_for_interest_rate
, staging_table.lh_contract_processing_fee
, staging_table.lh_escrow_holdback
, staging_table.lh_appraiser_license_number
, staging_table.lh_mcc_present
, staging_table.lh_grant_present
, staging_table.lh_cema
, staging_table.lh_supplemental_margin_company
, staging_table.lh_supplemental_margin_branch
, staging_table.lh_supplemental_margin_total
, staging_table.lh_concessions_renegotiations_amount
, staging_table.lh_fund_source_type
, staging_table.lh_purchase_contract_funding_date
, staging_table.lh_product_id
, staging_table.lh_community_second
, staging_table.lh_current_taxes_and_insurance
, staging_table.lh_multiple_applicants
, staging_table.lh_community_second_liability
, staging_table.lh_property_rights_type
, staging_table.lh_mbs_final_purchaser
, staging_table.lh_hmda_universal_loan_id
, staging_table.lh_lp_ace_eligible
, staging_table.lh_family_advantage_product
, staging_table.lh_effective_rate_sheet_datetime
, staging_table.lh_debt_to_income_excluding_mi
, staging_table.lh_clear_to_commit
, staging_table.lh_b2_first_name
, staging_table.lh_b2_last_name
, staging_table.lh_c2_first_name
, staging_table.lh_c2_last_name
, staging_table.lh_b3_first_name
, staging_table.lh_b3_last_name
, staging_table.lh_c3_first_name
, staging_table.lh_c3_last_name
, staging_table.lh_b4_first_name
, staging_table.lh_b4_last_name
, staging_table.lh_c4_first_name
, staging_table.lh_c4_last_name
, staging_table.lh_b5_first_name
, staging_table.lh_b5_last_name
, staging_table.lh_c5_first_name
, staging_table.lh_c5_last_name
, staging_table.lh_texas_home_equity_conversion
, staging_table.lh_interest_only_heloc
, staging_table.lh_interest_only_term_months
, staging_table.lh_investor_lock_product_name
, staging_table.lh_investor_lock_product_id
, staging_table.lh_rebuttable_presumption
, staging_table.lh_non_conforming
, staging_table.lh_num_deal_updates_since_update_pending
, staging_table.lh_borrower_engagement_percent
, staging_table.lh_loan_create_date
, staging_table.lh_high_balance_hit_percent
, staging_table.lh_new_york_payup_percent
, staging_table.lh_ship_date_to_custodian
, staging_table.lh_lock_vintage
, staging_table.lh_lock_series
, staging_table.lh_investor_total
, staging_table.lh_velocify_lead_id
, staging_table.lh_collateral_tracking_number
, staging_table.lh_qualified_mortgage_status_type
, staging_table.lh_charges_enabled_date
, staging_table.lh_application_date
, FALSE as data_source_deleted_flag
, now() AS data_source_updated_datetime
FROM staging_octane.loan_hedge staging_table
LEFT JOIN history_octane.loan_hedge history_table on staging_table.lh_pid = history_table.lh_pid and staging_table.lh_version = history_table.lh_version
WHERE history_table.lh_pid is NULL
UNION ALL
SELECT history_table.lh_pid
, history_table.lh_version+1
, history_table.lh_loan_pid
, history_table.lh_update_datetime
, history_table.lh_update_pending_datetime
, history_table.lh_transaction_status_date
, history_table.lh_loan_number
, history_table.lh_product_code
, history_table.lh_note_rate
, history_table.lh_loan_amount
, history_table.lh_lock_date
, history_table.lh_buy_side_lock_expires_date
, history_table.lh_lock_expiration_date
, history_table.lh_secondary_cost
, history_table.lh_total_cost_basis
, history_table.lh_total_lender_margin
, history_table.lh_stage
, history_table.lh_fund_date
, history_table.lh_allocation_date
, history_table.lh_estimated_fund_date
, history_table.lh_purchased_by_investor_date
, history_table.lh_commitment_number
, history_table.lh_property_occupancy
, history_table.lh_property_type
, history_table.lh_property_type_supplemental
, history_table.lh_property_state
, history_table.lh_property_zip
, history_table.lh_property_number_of_units
, history_table.lh_purchase_price
, history_table.lh_appraised_value
, history_table.lh_purpose
, history_table.lh_refinance_type
, history_table.lh_lien_position
, history_table.lh_impounds
, history_table.lh_buydown_type
, history_table.lh_buydown
, history_table.lh_ltv
, history_table.lh_original_ltv
, history_table.lh_cltv
, history_table.lh_original_cltv
, history_table.lh_effective_credit_score
, history_table.lh_doc_type
, history_table.lh_debt_to_income
, history_table.lh_prepayment_penalty
, history_table.lh_prepayment_penalty_term
, history_table.lh_interest_only
, history_table.lh_lock_type
, history_table.lh_lock_period
, history_table.lh_fees_collected_bps
, history_table.lh_channel
, history_table.lh_loan_officer
, history_table.lh_branch
, history_table.lh_broker
, history_table.lh_correspondent
, history_table.lh_origination_source
, history_table.lh_investor
, history_table.lh_investor_total_price
, history_table.lh_investor_base_price
, history_table.lh_investor_srp_paid
, history_table.lh_investor_loan_number
, history_table.lh_pmi
, history_table.lh_pmi_percent
, history_table.lh_mi_cert_number
, history_table.lh_srp_paid
, history_table.lh_discount_points
, history_table.lh_date_docs_back
, history_table.lh_note_date
, history_table.lh_close_date
, history_table.lh_first_payment_date
, history_table.lh_last_payment_date
, history_table.lh_next_scheduled_payment_due_date
, history_table.lh_scheduled_principal_and_interest
, history_table.lh_current_principal_and_interest
, history_table.lh_minimum_principal_and_interest
, history_table.lh_current_unpaid_principal_balance
, history_table.lh_original_interest_rate
, history_table.lh_maturity_date
, history_table.lh_amortization_term
, history_table.lh_yearly_payment_cap
, history_table.lh_arm_margin
, history_table.lh_arm_adjustment_date
, history_table.lh_first_arm_period
, history_table.lh_first_arm_adjustment_cap
, history_table.lh_arm_life_floor
, history_table.lh_arm_life_ceiling
, history_table.lh_first_arm_payment_adjustment_date
, history_table.lh_arm_period_after_first
, history_table.lh_arm_adjustment_cap_after_first
, history_table.lh_first_payment_cap
, history_table.lh_payment_cap_option
, history_table.lh_neg_am_flag
, history_table.lh_maximum_negative_amortization
, history_table.lh_arm_convertible
, history_table.lh_arm_index
, history_table.lh_dual_loan_flag
, history_table.lh_other_loan_number
, history_table.lh_agency_extract_fields
, history_table.lh_warehouse_bank
, history_table.lh_wire_amount
, history_table.lh_credit_rating_agency_fields
, history_table.lh_levels_fields
, history_table.lh_data_fields
, history_table.lh_loan_status
, history_table.lh_suspense_yes_no
, history_table.lh_loan_type
, history_table.lh_hud_borr_paid_by_for_borr_other_amount
, history_table.lh_fees_line_user_def_fee_one_borr
, history_table.lh_uw_suspended_cleared_date
, history_table.lh_underwriting_suspended_date
, history_table.lh_line_orig_charge
, history_table.lh_amortization_type
, history_table.lh_milestone
, history_table.lh_msa
, history_table.lh_county_code
, history_table.lh_ship_date_to_investor
, history_table.lh_borrower_last_name
, history_table.lh_purchase_advice_suspense_fee
, history_table.lh_purchase_advice_early_delivery_amount
, history_table.lh_purchase_advice_llpa
, history_table.lh_purchase_advice_fmna
, history_table.lh_purchase_advice_rp
, history_table.lh_lock_info_relock_amount
, history_table.lh_lock_info_loan_basis
, history_table.lh_lock_info_lock_request_fulfilled_date_time
, history_table.lh_lock_info_rate_lock_request_rate_sheet_id
, history_table.lh_current_status_change_date
, history_table.lh_aus_type
, history_table.lh_buy_side_base_arm_margin
, history_table.lh_uldd_poolid
, history_table.lh_warehouse_co_name
, history_table.lh_underwriting_investor_eligibility_wells_fargo
, history_table.lh_underwriting_investor_eligibility_chase
, history_table.lh_du_fail_reason
, history_table.lh_lpmi_total_costs_on_lock
, history_table.lh_lpmi_after_lock_required
, history_table.lh_lpmi_after_lock_bps
, history_table.lh_mi_company_name_type
, history_table.lh_lpmi_frequency
, history_table.lh_lpmi_estimated_amount_of_lender_paid_mi
, history_table.lh_mortgage_insurance_premium_source_type
, history_table.lh_loan_amount_repeat
, history_table.lh_product_code_repeat
, history_table.lh_note_rate_repeat
, history_table.lh_loan_info_loan_id
, history_table.lh_salable_loan
, history_table.lh_sale_hold
, history_table.lh_sale_hold_comments
, history_table.lh_pf_disbursement_ledger_date
, history_table.lh_aus_eligibility
, history_table.lh_texas_cash_out
, history_table.lh_acceptable_du
, history_table.lh_acceptable_lp
, history_table.lh_financed_property_count
, history_table.lh_payoff_primary_lien_holder_company
, history_table.lh_payoff_junior_lien_holder_company
, history_table.lh_base_loan_amount
, history_table.lh_funding_authorized
, history_table.lh_credit_committee_fico_exception
, history_table.lh_home_ready_eligibility
, history_table.lh_home_ready_borr_acceptance
, history_table.lh_home_ready_eligibility_review
, history_table.lh_home_possible_eligibility
, history_table.lh_home_possible_eligibility_review
, history_table.lh_piw
, history_table.lh_piw_fee
, history_table.lh_uw_investor_eligibility_fnma
, history_table.lh_uw_investor_eligibility_fhlmc
, history_table.lh_appraisal_form
, history_table.lh_ext_cos_total_amt
, history_table.lh_fnmcu_risk_score
, history_table.lh_borrower_income_verification
, history_table.lh_co_borrower_income_verification
, history_table.lh_day_one_income_verification_available
, history_table.lh_subject_property_estimated_value
, history_table.lh_transaction_status
, history_table.lh_buy_status
, history_table.lh_appraisal_exists
, history_table.lh_du_piw_eligible
, history_table.lh_lp_appraisal_waiver_eligible
, history_table.lh_borrower_first_name
, history_table.lh_co_borrower_first_name
, history_table.lh_co_borrower_last_name
, history_table.lh_total_borrower_income
, history_table.lh_subject_property_city
, history_table.lh_subject_property_county
, history_table.lh_subject_property_zip
, history_table.lh_borrower_decision_credit_score
, history_table.lh_co_borrower_decision_credit_score
, history_table.lh_underwriter_disposition
, history_table.lh_underwrite_risk_assessment_type
, history_table.lh_subject_property_address
, history_table.lh_original_lock_date
, history_table.lh_original_lock_period
, history_table.lh_borrower_income_docs_required_count
, history_table.lh_borrower_income_docs_fulfilled_count
, history_table.lh_borrower_income_docs_approved_count
, history_table.lh_borrower_asset_docs_required_count
, history_table.lh_borrower_asset_docs_fulfilled_count
, history_table.lh_borrower_asset_docs_approved_count
, history_table.lh_borrower_credit_docs_required_count
, history_table.lh_borrower_credit_docs_fulfilled_count
, history_table.lh_borrower_credit_docs_approved_count
, history_table.lh_initial_uw_submit_date_time
, history_table.lh_cd_clear_date
, history_table.lh_lender_concession_total_approved_amount
, history_table.lh_relock_fee_gross_amount
, history_table.lh_relock_fee_amount_less_concessions
, history_table.lh_relock_fee_amount_concessed
, history_table.lh_lock_extension_fee_gross_amount
, history_table.lh_lock_extension_fee_amount_less_concessions
, history_table.lh_lock_extension_fee_amount_concessed
, history_table.lh_general_lender_concessions_amount_non_itemized
, history_table.lh_day_one_concessions
, history_table.lh_investor_lock_commitment_type
, history_table.lh_signed_closing_doc_received_datetime
, history_table.lh_geocoding_msa_code
, history_table.lh_geocoding_state_code
, history_table.lh_geocoding_county_code
, history_table.lh_geocoding_census_tract
, history_table.lh_tolerance_cure_amount
, history_table.lh_self_employed_flag
, history_table.lh_first_time_homebuyer
, history_table.lh_mortgage_insurance_lpmi_rate_adjustment
, history_table.lh_eligible_for_qm_status
, history_table.lh_safe_harbor_test_passed
, history_table.lh_hpml
, history_table.lh_hoepa
, history_table.lh_funding_status
, history_table.lh_early_funding
, history_table.lh_early_funding_date
, history_table.lh_lqa_purchase_eligibility_type
, history_table.lh_transferred_appraisal
, history_table.lh_appraisal_cu_risk_score
, history_table.lh_mi_upfront_rate
, history_table.lh_loan_funding_requested_date
, history_table.lh_student_loan_cash_out
, history_table.lh_octane_high_balance
, history_table.lh_borrower_final_price
, history_table.lh_charge_credit_for_interest_rate
, history_table.lh_contract_processing_fee
, history_table.lh_escrow_holdback
, history_table.lh_appraiser_license_number
, history_table.lh_mcc_present
, history_table.lh_grant_present
, history_table.lh_cema
, history_table.lh_supplemental_margin_company
, history_table.lh_supplemental_margin_branch
, history_table.lh_supplemental_margin_total
, history_table.lh_concessions_renegotiations_amount
, history_table.lh_fund_source_type
, history_table.lh_purchase_contract_funding_date
, history_table.lh_product_id
, history_table.lh_community_second
, history_table.lh_current_taxes_and_insurance
, history_table.lh_multiple_applicants
, history_table.lh_community_second_liability
, history_table.lh_property_rights_type
, history_table.lh_mbs_final_purchaser
, history_table.lh_hmda_universal_loan_id
, history_table.lh_lp_ace_eligible
, history_table.lh_family_advantage_product
, history_table.lh_effective_rate_sheet_datetime
, history_table.lh_debt_to_income_excluding_mi
, history_table.lh_clear_to_commit
, history_table.lh_b2_first_name
, history_table.lh_b2_last_name
, history_table.lh_c2_first_name
, history_table.lh_c2_last_name
, history_table.lh_b3_first_name
, history_table.lh_b3_last_name
, history_table.lh_c3_first_name
, history_table.lh_c3_last_name
, history_table.lh_b4_first_name
, history_table.lh_b4_last_name
, history_table.lh_c4_first_name
, history_table.lh_c4_last_name
, history_table.lh_b5_first_name
, history_table.lh_b5_last_name
, history_table.lh_c5_first_name
, history_table.lh_c5_last_name
, history_table.lh_texas_home_equity_conversion
, history_table.lh_interest_only_heloc
, history_table.lh_interest_only_term_months
, history_table.lh_investor_lock_product_name
, history_table.lh_investor_lock_product_id
, history_table.lh_rebuttable_presumption
, history_table.lh_non_conforming
, history_table.lh_num_deal_updates_since_update_pending
, history_table.lh_borrower_engagement_percent
, history_table.lh_loan_create_date
, history_table.lh_high_balance_hit_percent
, history_table.lh_new_york_payup_percent
, history_table.lh_ship_date_to_custodian
, history_table.lh_lock_vintage
, history_table.lh_lock_series
, history_table.lh_investor_total
, history_table.lh_velocify_lead_id
, history_table.lh_collateral_tracking_number
, history_table.lh_qualified_mortgage_status_type
, history_table.lh_charges_enabled_date
, history_table.lh_application_date
, TRUE as data_source_deleted_flag
, now() AS data_source_updated_datetime
FROM history_octane.loan_hedge history_table
LEFT JOIN staging_octane.loan_hedge staging_table on staging_table.lh_pid = history_table.lh_pid
WHERE staging_table.lh_pid is NULL
  AND not exists (select 1 from history_octane.loan_hedge deleted_records where deleted_records.lh_pid = history_table.lh_pid and deleted_records.data_source_deleted_flag = True);')
)

, updated_table_input_step AS (
    UPDATE mdi.table_input_step
        SET sql = updated_table_input_sql.sql
        FROM updated_table_input_sql
            , mdi.table_output_step
        WHERE table_input_step.process_dwid = table_output_step.process_dwid
            AND table_output_step.target_schema = 'history_octane'
            AND table_output_step.target_table = updated_table_input_sql.table_name
)

SELECT 'Finished inserting metadata for new columns: loan_hedge.lh_charges_enabled_date, loan_hedge' ||
       '.lh_application_date';
