--
-- EDW - DMI Passport data load (SP-7) (https://app.asana.com/0/0/1182841661698329 )
--

-- populate edw_table_definition with data for newly created table ingress.dmi.passport
WITH cte_edw_table_definition as (INSERT INTO mdi.edw_table_definition (database_name, schema_name, table_name, primary_source_edw_table_definition_dwid)
    VALUES ('ingress', 'dmi', 'passport', NULL)
    RETURNING dwid)

    , cte_new_fields (field_name, key_field_flag) AS (
    VALUES ('etl_batch_id',FALSE)
         , ('data_source_dwid',FALSE)
         , ('input_filename',FALSE)
         , ('loan_number',FALSE)
         , ('old_loan_number',FALSE)
         , ('new_servicer_loan_number',FALSE)
         , ('user_03_position_field_3a',FALSE)
         , ('first_due_date',FALSE)
         , ('loan_closing_date',FALSE)
         , ('loan_purpose_code',FALSE)
         , ('loan_purpose_code_description',FALSE)
         , ('note_date',FALSE)
         , ('acquisition_date',FALSE)
         , ('original_interest_rate',FALSE)
         , ('original_loan_term',FALSE)
         , ('original_mortgage_amount',FALSE)
         , ('original_p_and_i_amount',FALSE)
         , ('original_property_value_amount',FALSE)
         , ('original_second_interest_rate',FALSE)
         , ('original_second_loan_term',FALSE)
         , ('original_second_mtg_amount',FALSE)
         , ('original_second_p_and_i',FALSE)
         , ('original_loan_to_value_ratio',FALSE)
         , ('annual_interest_rate',FALSE)
         , ('arm_indicator',FALSE)
         , ('drafting_indicator',FALSE)
         , ('draft_option_code',FALSE)
         , ('draft_delay_days_quantity',FALSE)
         , ('billing_mode',FALSE)
         , ('coupon_tape_date',FALSE)
         , ('coupon_bill_last_create_date',FALSE)
         , ('def_int_balance',FALSE)
         , ('distribution_type',FALSE)
         , ('loan_to_value_ratio',FALSE)
         , ('first_p_and_i_amount',FALSE)
         , ('first_principal_balance',FALSE)
         , ('el_status_indicator',FALSE)
         , ('interest_only_expire_date',FALSE)
         , ('interest_only_loan_indicator',FALSE)
         , ('qualified_mortgage_code',FALSE)
         , ('qualified_mortgage_code_description',FALSE)
         , ('higher_priced_indicator',FALSE)
         , ('higher_priced_indicator_description',FALSE)
         , ('high_cost_type',FALSE)
         , ('high_cost_type_description',FALSE)
         , ('escrow_waiver_code',FALSE)
         , ('escrow_waiver_code_description',FALSE)
         , ('escrow_waiver_date',FALSE)
         , ('investor_loan_number',FALSE)
         , ('investor_id',FALSE)
         , ('category_code',FALSE)
         , ('first_service_fee_rate',FALSE)
         , ('pool_number',FALSE)
         , ('pool_class_code',FALSE)
         , ('pool_contract_number',FALSE)
         , ('gse_code',FALSE)
         , ('gse_code_description',FALSE)
         , ('hi_type',FALSE)
         , ('hi_type_description',FALSE)
         , ('lo_type',FALSE)
         , ('lo_type_description',FALSE)
         , ('development_type',FALSE)
         , ('development_type_description',FALSE)
         , ('second_hi_type',FALSE)
         , ('bl_balloon_status_code',FALSE)
         , ('bl_balloon_status_code_description',FALSE)
         , ('balloon_status_code',FALSE)
         , ('balloon_status_code_description',FALSE)
         , ('loan_matures_date',FALSE)
         , ('loan_term',FALSE)
         , ('remaining_term',FALSE)
         , ('man_code',FALSE)
         , ('man_code_description',FALSE)
         , ('mers_id',FALSE)
         , ('mers_original_mortgagee_ind',FALSE)
         , ('mers_original_mortgagee_ind_description',FALSE)
         , ('mers_registration_status_code',FALSE)
         , ('mers_registration_date',FALSE)
         , ('mers_id_number_status_code',FALSE)
         , ('mers_assigned_date',FALSE)
         , ('next_payment_due_date',FALSE)
         , ('last_full_payment_date',FALSE)
         , ('due_date_day_portion_parsed',FALSE)
         , ('payment_period',FALSE)
         , ('payment_option_code',FALSE)
         , ('payment_option_code_description',FALSE)
         , ('suspense_balance',FALSE)
         , ('nsf_fee_balance',FALSE)
         , ('total_monthly_payment',FALSE)
         , ('billing_name',FALSE)
         , ('billing_address_line_2',FALSE)
         , ('co_mortgagor_name',FALSE)
         , ('billing_address_line_3',FALSE)
         , ('billing_address_line_4',FALSE)
         , ('billing_city_name',FALSE)
         , ('foreign_address_indicator',FALSE)
         , ('billing_state',FALSE)
         , ('billing_zip_code',FALSE)
         , ('telephone_number',FALSE)
         , ('telephone_code',FALSE)
         , ('mortgagor_prefered_lang_code',FALSE)
         , ('second_telephone_number',FALSE)
         , ('sec_mortgagor_ss_number',FALSE)
         , ('sec_co_mortgagor_ss_number',FALSE)
         , ('property_street_address',FALSE)
         , ('property_unit_number',FALSE)
         , ('city_name',FALSE)
         , ('property_alpha_state_code',FALSE)
         , ('property_zip_code',FALSE)
         , ('county_code',FALSE)
         , ('fips_county_code',FALSE)
         , ('fips_state_code',FALSE)
         , ('occupancy_code',FALSE)
         , ('occupancy_code_description',FALSE)
         , ('property_state_code',FALSE)
         , ('number_of_units',FALSE)
         , ('appraisal_date',FALSE)
         , ('property_value_amount',FALSE)
         , ('property_type',FALSE)
         , ('property_type_fnma_code',FALSE)
         , ('property_type_fnma_code_description',FALSE)
         , ('occupancy_current_status_code',FALSE)
         , ('occupancy_current_status_code_description',FALSE)
         , ('ownership_type',FALSE)
         , ('ownership_type_description',FALSE)
         , ('flood_community_start_date',FALSE)
         , ('flood_program_type',FALSE)
         , ('flood_loma_revision_code',FALSE)
         , ('flood_loma_determination_date',FALSE)
         , ('flood_contract_type',FALSE)
         , ('flood_community_number',FALSE)
         , ('flood_panel_number',FALSE)
         , ('flood_zone_position_1',FALSE)
         , ('flood_zone_position_2_and_3',FALSE)
         , ('flood_suffix_number',FALSE)
         , ('flood_zone_partial_indicator',FALSE)
         , ('flood_firm_effective_date',FALSE)
         , ('flood_mapping_company_id',FALSE)
         , ('flood_certification_number',FALSE)
         , ('grace_days',FALSE)
         , ('late_charge_amount',FALSE)
         , ('late_charge_code',FALSE)
         , ('late_charge_code_description',FALSE)
         , ('late_charge_factor',FALSE)
         , ('maximum_late_charge_amount',FALSE)
         , ('minimum_late_charge_amount',FALSE)
         , ('delinquency_class_code',FALSE)
         , ('delinquency_class_code_description',FALSE)
         , ('secondary_phone_code',FALSE)
         , ('secondary_phone_number',FALSE)
         , ('escrow_advance_balance',FALSE)
         , ('escrow_balance',FALSE)
         , ('escrow_replace_resrv_balance',FALSE)
         , ('hazard_ins_monthly_amount',FALSE)
         , ('replace_reserve_amount',FALSE)
         , ('restricted_escrow_balance',FALSE)
         , ('t_and_i_monthly_amount',FALSE)
         , ('a_and_h_premium_amount',FALSE)
         , ('life_premium_amount',FALSE)
         , ('interest_paid_through_date',FALSE)
         , ('ln_mod_code',FALSE)
         , ('ln_mod_code_description',FALSE)
         , ('last_analysis_date',FALSE)
         , ('last_analysis_effective_date',FALSE)
         , ('last_analysis_os_spread_months',FALSE)
         , ('mi_monthly_amount',FALSE)
         , ('mi_term',FALSE)
         , ('mi_disbursement_amount',FALSE)
         , ('mi_disbursement_due_date',FALSE)
         , ('mi_mid_point_date',FALSE)
         , ('mi_termination_date',FALSE)
         , ('mi_cancellation_date',FALSE)
         , ('mi_request_to_cancel_date',FALSE)
         , ('pmi_cancellation_reason_code',FALSE)
         , ('pmi_cancellation_reason_code_description',FALSE)
         , ('va_loan_number',FALSE)
         , ('va_lin_check_digit_number',FALSE)
         , ('recover_corp_advance_balance',FALSE)
         , ('third_party_recoverable_ca_bal',FALSE)
         , ('non_rec_corp_advance_balance',FALSE)
         , ('second_principal_balance',FALSE)
         , ('actual_deferred_balance',FALSE)
         , ('ytd_principal_paid_amount',FALSE)
         , ('ytd_interest_amount',FALSE)
         , ('ytd_tax_amount',FALSE)
         , ('ytd_ioe_amount',FALSE)
         , ('ytd_hazard_amt',FALSE)
         , ('ytd_lien_amount',FALSE)
         , ('ytd_mip_amount',FALSE)
         , ('ytd_nsf_total',FALSE)
         , ('ytd_restricted_ioe_amount',FALSE)
         , ('ytd_late_charge_amount',FALSE)
         , ('prepay_penalty_indicator',FALSE)
         , ('ppp_header_id',FALSE)
         , ('ppp_header_name',FALSE)
         , ('user_05_position_field_2a',FALSE)
         , ('purchase_price',FALSE)
         , ('interest_calc_option_code',FALSE)
         , ('the_360_365_factor',FALSE)
         , ('the_360_365_factor_description',FALSE)
         , ('assumption_code',FALSE)
         , ('assumption_code_description',FALSE)
         , ('bill_code',FALSE)
         , ('bill_code_description',FALSE)
         , ('rhs_borrower_id',FALSE)
         , ('opt_ins_plan_id',FALSE)
         , ('certificate_number_1',FALSE)
         , ('certificate_number_2',FALSE)
         , ('opt_ins_disbursement_amount',FALSE)
         , ('opt_ins_disbursement_due_date',FALSE)
         , ('imminent_default_fico_score',FALSE)
         , ('imminent_default_fico_date',FALSE)
         , ('points_paid_by_borrower',FALSE)
         , ('third_party_draft_code',FALSE)
         , ('third_party_draft_code_description',FALSE)
         , ('employee_code',FALSE)
         , ('zone',FALSE)
         , ('sec_mortgagor_birth_date',FALSE)
         , ('sec_co_mortgagor_birth_date',FALSE)
         , ('email_address',FALSE)
         , ('co_mortgagor_email_address',FALSE)
         , ('servicing_sold_id',FALSE)
)
    -- populate edw_field_definition with the list of above fields
    , cte_edw_field_definition as (INSERT INTO mdi.edw_field_definition (edw_table_definition_dwid, field_name, key_field_flag)
    SELECT cte_edw_table_definition.dwid, cte_new_fields.field_name, cte_new_fields.key_field_flag
        FROM cte_edw_table_definition, cte_new_fields)

SELECT 'Done adding table and field definitions for ingress.dmi.passport';


-- Create a Metadata Injection (MDI) configuration with the following properties:
-- Process Name: SP-7
-- Process Description: Load DMI Passport file to ingress database

-- The following statement adds an ETL configuration to populate dmi.passport (SP-7)
WITH cte_process as (INSERT INTO mdi.process (name, description)    -- mdi.process
    VALUES ('SP-7', 'Source data ETL to populate dmi.passport from a CSV file')
    RETURNING dwid)

    , cte_csv_file_input_step as (INSERT INTO mdi.csv_file_input_step ( process_dwid,
                                                                        header_present,
                                                                        delimiter,
                                                                        enclosure,
                                                                        buffersize,
                                                                        lazy_conversion,
                                                                        newline_possible,
                                                                        add_filename_result,
                                                                        file_format,
                                                                        file_encoding,
                                                                        include_filename,
                                                                        process_in_parallel,
                                                                        filename_field,
                                                                        row_num_field,
                                                                        data_source_dwid)
    SELECT cte_process.dwid,
           'Y',
           ',',
           '"',
           1024,
           'N',
           'N',
           'N',
           'mixed',
           'UTF-8',
           'Y',
           'N',
           NULL,
           NULL,
           3 -- 3 = DMI in staging.star_common.data_source
        FROM
            cte_process
    RETURNING dwid)

   , cte_csv_file_input_field_list (field_name, field_type, field_format, field_length, field_precision, field_trim_type, field_order) AS (
    VALUES  ('loan_number', 'String', NULL, -1, -1, 'none', 1)
         , ('old_loan_number', 'String', NULL, -1, -1, 'none', 2)
         , ('new_servicer_loan_number', 'String', NULL, -1, -1, 'none', 3)
         , ('user_03_position_field_3a', 'String', NULL, -1, -1, 'none', 4)
         , ('first_due_date', 'String', NULL, -1, -1, 'none', 5)
         , ('loan_closing_date', 'String', NULL, -1, -1, 'none', 6)
         , ('loan_purpose_code', 'String', NULL, -1, -1, 'none', 7)
         , ('loan_purpose_code_description', 'String', NULL, -1, -1, 'none', 8)
         , ('note_date', 'String', NULL, -1, -1, 'none', 9)
         , ('acquisition_date', 'String', NULL, -1, -1, 'none', 10)
         , ('original_interest_rate', 'String', NULL, -1, -1, 'none', 11)
         , ('original_loan_term', 'String', NULL, -1, -1, 'none', 12)
         , ('original_mortgage_amount', 'String', NULL, -1, -1, 'none', 13)
         , ('original_p_and_i_amount', 'String', NULL, -1, -1, 'none', 14)
         , ('original_property_value_amount', 'String', NULL, -1, -1, 'none', 15)
         , ('original_second_interest_rate', 'String', NULL, -1, -1, 'none', 16)
         , ('original_second_loan_term', 'String', NULL, -1, -1, 'none', 17)
         , ('original_second_mtg_amount', 'String', NULL, -1, -1, 'none', 18)
         , ('original_second_p_and_i', 'String', NULL, -1, -1, 'none', 19)
         , ('original_loan_to_value_ratio', 'String', NULL, -1, -1, 'none', 20)
         , ('annual_interest_rate', 'String', NULL, -1, -1, 'none', 21)
         , ('arm_indicator', 'String', NULL, -1, -1, 'none', 22)
         , ('drafting_indicator', 'String', NULL, -1, -1, 'none', 23)
         , ('draft_option_code', 'String', NULL, -1, -1, 'none', 24)
         , ('draft_delay_days_quantity', 'String', NULL, -1, -1, 'none', 25)
         , ('billing_mode', 'String', NULL, -1, -1, 'none', 26)
         , ('coupon_tape_date', 'String', NULL, -1, -1, 'none', 27)
         , ('coupon_bill_last_create_date', 'String', NULL, -1, -1, 'none', 28)
         , ('def_int_balance', 'String', NULL, -1, -1, 'none', 29)
         , ('distribution_type', 'String', NULL, -1, -1, 'none', 30)
         , ('loan_to_value_ratio', 'String', NULL, -1, -1, 'none', 31)
         , ('first_p_and_i_amount', 'String', NULL, -1, -1, 'none', 32)
         , ('first_principal_balance', 'String', NULL, -1, -1, 'none', 33)
         , ('el_status_indicator', 'String', NULL, -1, -1, 'none', 34)
         , ('interest_only_expire_date', 'String', NULL, -1, -1, 'none', 35)
         , ('interest_only_loan_indicator', 'String', NULL, -1, -1, 'none', 36)
         , ('qualified_mortgage_code', 'String', NULL, -1, -1, 'none', 37)
         , ('qualified_mortgage_code_description', 'String', NULL, -1, -1, 'none', 38)
         , ('higher_priced_indicator', 'String', NULL, -1, -1, 'none', 39)
         , ('higher_priced_indicator_description', 'String', NULL, -1, -1, 'none', 40)
         , ('high_cost_type', 'String', NULL, -1, -1, 'none', 41)
         , ('high_cost_type_description', 'String', NULL, -1, -1, 'none', 42)
         , ('escrow_waiver_code', 'String', NULL, -1, -1, 'none', 43)
         , ('escrow_waiver_code_description', 'String', NULL, -1, -1, 'none', 44)
         , ('escrow_waiver_date', 'String', NULL, -1, -1, 'none', 45)
         , ('investor_loan_number', 'String', NULL, -1, -1, 'none', 46)
         , ('investor_id', 'String', NULL, -1, -1, 'none', 47)
         , ('category_code', 'String', NULL, -1, -1, 'none', 48)
         , ('first_service_fee_rate', 'String', NULL, -1, -1, 'none', 49)
         , ('pool_number', 'String', NULL, -1, -1, 'none', 50)
         , ('pool_class_code', 'String', NULL, -1, -1, 'none', 51)
         , ('pool_contract_number', 'String', NULL, -1, -1, 'none', 52)
         , ('gse_code', 'String', NULL, -1, -1, 'none', 53)
         , ('gse_code_description', 'String', NULL, -1, -1, 'none', 54)
         , ('hi_type', 'String', NULL, -1, -1, 'none', 55)
         , ('hi_type_description', 'String', NULL, -1, -1, 'none', 56)
         , ('lo_type', 'String', NULL, -1, -1, 'none', 57)
         , ('lo_type_description', 'String', NULL, -1, -1, 'none', 58)
         , ('development_type', 'String', NULL, -1, -1, 'none', 59)
         , ('development_type_description', 'String', NULL, -1, -1, 'none', 60)
         , ('second_hi_type', 'String', NULL, -1, -1, 'none', 61)
         , ('bl_balloon_status_code', 'String', NULL, -1, -1, 'none', 62)
         , ('bl_balloon_status_code_description', 'String', NULL, -1, -1, 'none', 63)
         , ('balloon_status_code', 'String', NULL, -1, -1, 'none', 64)
         , ('balloon_status_code_description', 'String', NULL, -1, -1, 'none', 65)
         , ('loan_matures_date', 'String', NULL, -1, -1, 'none', 66)
         , ('loan_term', 'String', NULL, -1, -1, 'none', 67)
         , ('remaining_term', 'String', NULL, -1, -1, 'none', 68)
         , ('man_code', 'String', NULL, -1, -1, 'none', 69)
         , ('man_code_description', 'String', NULL, -1, -1, 'none', 70)
         , ('mers_id', 'String', NULL, -1, -1, 'none', 71)
         , ('mers_original_mortgagee_ind', 'String', NULL, -1, -1, 'none', 72)
         , ('mers_original_mortgagee_ind_description', 'String', NULL, -1, -1, 'none', 73)
         , ('mers_registration_status_code', 'String', NULL, -1, -1, 'none', 74)
         , ('mers_registration_date', 'String', NULL, -1, -1, 'none', 75)
         , ('mers_id_number_status_code', 'String', NULL, -1, -1, 'none', 76)
         , ('mers_assigned_date', 'String', NULL, -1, -1, 'none', 77)
         , ('next_payment_due_date', 'String', NULL, -1, -1, 'none', 78)
         , ('last_full_payment_date', 'String', NULL, -1, -1, 'none', 79)
         , ('due_date_day_portion_parsed', 'String', NULL, -1, -1, 'none', 80)
         , ('payment_period', 'String', NULL, -1, -1, 'none', 81)
         , ('payment_option_code', 'String', NULL, -1, -1, 'none', 82)
         , ('payment_option_code_description', 'String', NULL, -1, -1, 'none', 83)
         , ('suspense_balance', 'String', NULL, -1, -1, 'none', 84)
         , ('nsf_fee_balance', 'String', NULL, -1, -1, 'none', 85)
         , ('total_monthly_payment', 'String', NULL, -1, -1, 'none', 86)
         , ('billing_name', 'String', NULL, -1, -1, 'none', 87)
         , ('billing_address_line_2', 'String', NULL, -1, -1, 'none', 88)
         , ('co_mortgagor_name', 'String', NULL, -1, -1, 'none', 89)
         , ('billing_address_line_3', 'String', NULL, -1, -1, 'none', 90)
         , ('billing_address_line_4', 'String', NULL, -1, -1, 'none', 91)
         , ('billing_city_name', 'String', NULL, -1, -1, 'none', 92)
         , ('foreign_address_indicator', 'String', NULL, -1, -1, 'none', 93)
         , ('billing_state', 'String', NULL, -1, -1, 'none', 94)
         , ('billing_zip_code', 'String', NULL, -1, -1, 'none', 95)
         , ('telephone_number', 'String', NULL, -1, -1, 'none', 96)
         , ('telephone_code', 'String', NULL, -1, -1, 'none', 97)
         , ('mortgagor_prefered_lang_code', 'String', NULL, -1, -1, 'none', 98)
         , ('second_telephone_number', 'String', NULL, -1, -1, 'none', 99)
         , ('sec_mortgagor_ss_number', 'String', NULL, -1, -1, 'none', 100)
         , ('sec_co_mortgagor_ss_number', 'String', NULL, -1, -1, 'none', 101)
         , ('property_street_address', 'String', NULL, -1, -1, 'none', 102)
         , ('property_unit_number', 'String', NULL, -1, -1, 'none', 103)
         , ('city_name', 'String', NULL, -1, -1, 'none', 104)
         , ('property_alpha_state_code', 'String', NULL, -1, -1, 'none', 105)
         , ('property_zip_code', 'String', NULL, -1, -1, 'none', 106)
         , ('county_code', 'String', NULL, -1, -1, 'none', 107)
         , ('fips_county_code', 'String', NULL, -1, -1, 'none', 108)
         , ('fips_state_code', 'String', NULL, -1, -1, 'none', 109)
         , ('occupancy_code', 'String', NULL, -1, -1, 'none', 110)
         , ('occupancy_code_description', 'String', NULL, -1, -1, 'none', 111)
         , ('property_state_code', 'String', NULL, -1, -1, 'none', 112)
         , ('number_of_units', 'String', NULL, -1, -1, 'none', 113)
         , ('appraisal_date', 'String', NULL, -1, -1, 'none', 114)
         , ('property_value_amount', 'String', NULL, -1, -1, 'none', 115)
         , ('property_type', 'String', NULL, -1, -1, 'none', 116)
         , ('property_type_fnma_code', 'String', NULL, -1, -1, 'none', 117)
         , ('property_type_fnma_code_description', 'String', NULL, -1, -1, 'none', 118)
         , ('occupancy_current_status_code', 'String', NULL, -1, -1, 'none', 119)
         , ('occupancy_current_status_code_description', 'String', NULL, -1, -1, 'none', 120)
         , ('ownership_type', 'String', NULL, -1, -1, 'none', 121)
         , ('ownership_type_description', 'String', NULL, -1, -1, 'none', 122)
         , ('flood_community_start_date', 'String', NULL, -1, -1, 'none', 123)
         , ('flood_program_type', 'String', NULL, -1, -1, 'none', 124)
         , ('flood_loma_revision_code', 'String', NULL, -1, -1, 'none', 125)
         , ('flood_loma_determination_date', 'String', NULL, -1, -1, 'none', 126)
         , ('flood_contract_type', 'String', NULL, -1, -1, 'none', 127)
         , ('flood_community_number', 'String', NULL, -1, -1, 'none', 128)
         , ('flood_panel_number', 'String', NULL, -1, -1, 'none', 129)
         , ('flood_zone_position_1', 'String', NULL, -1, -1, 'none', 130)
         , ('flood_zone_position_2_and_3', 'String', NULL, -1, -1, 'none', 131)
         , ('flood_suffix_number', 'String', NULL, -1, -1, 'none', 132)
         , ('flood_zone_partial_indicator', 'String', NULL, -1, -1, 'none', 133)
         , ('flood_firm_effective_date', 'String', NULL, -1, -1, 'none', 134)
         , ('flood_mapping_company_id', 'String', NULL, -1, -1, 'none', 135)
         , ('flood_certification_number', 'String', NULL, -1, -1, 'none', 136)
         , ('grace_days', 'String', NULL, -1, -1, 'none', 137)
         , ('late_charge_amount', 'String', NULL, -1, -1, 'none', 138)
         , ('late_charge_code', 'String', NULL, -1, -1, 'none', 139)
         , ('late_charge_code_description', 'String', NULL, -1, -1, 'none', 140)
         , ('late_charge_factor', 'String', NULL, -1, -1, 'none', 141)
         , ('maximum_late_charge_amount', 'String', NULL, -1, -1, 'none', 142)
         , ('minimum_late_charge_amount', 'String', NULL, -1, -1, 'none', 143)
         , ('delinquency_class_code', 'String', NULL, -1, -1, 'none', 144)
         , ('delinquency_class_code_description', 'String', NULL, -1, -1, 'none', 145)
         , ('secondary_phone_code', 'String', NULL, -1, -1, 'none', 146)
         , ('secondary_phone_number', 'String', NULL, -1, -1, 'none', 147)
         , ('escrow_advance_balance', 'String', NULL, -1, -1, 'none', 148)
         , ('escrow_balance', 'String', NULL, -1, -1, 'none', 149)
         , ('escrow_replace_resrv_balance', 'String', NULL, -1, -1, 'none', 150)
         , ('hazard_ins_monthly_amount', 'String', NULL, -1, -1, 'none', 151)
         , ('replace_reserve_amount', 'String', NULL, -1, -1, 'none', 152)
         , ('restricted_escrow_balance', 'String', NULL, -1, -1, 'none', 153)
         , ('t_and_i_monthly_amount', 'String', NULL, -1, -1, 'none', 154)
         , ('a_and_h_premium_amount', 'String', NULL, -1, -1, 'none', 155)
         , ('life_premium_amount', 'String', NULL, -1, -1, 'none', 156)
         , ('interest_paid_through_date', 'String', NULL, -1, -1, 'none', 157)
         , ('ln_mod_code', 'String', NULL, -1, -1, 'none', 158)
         , ('ln_mod_code_description', 'String', NULL, -1, -1, 'none', 159)
         , ('last_analysis_date', 'String', NULL, -1, -1, 'none', 160)
         , ('last_analysis_effective_date', 'String', NULL, -1, -1, 'none', 161)
         , ('last_analysis_os_spread_months', 'String', NULL, -1, -1, 'none', 162)
         , ('mi_monthly_amount', 'String', NULL, -1, -1, 'none', 163)
         , ('mi_term', 'String', NULL, -1, -1, 'none', 164)
         , ('mi_disbursement_amount', 'String', NULL, -1, -1, 'none', 165)
         , ('mi_disbursement_due_date', 'String', NULL, -1, -1, 'none', 166)
         , ('mi_mid_point_date', 'String', NULL, -1, -1, 'none', 167)
         , ('mi_termination_date', 'String', NULL, -1, -1, 'none', 168)
         , ('mi_cancellation_date', 'String', NULL, -1, -1, 'none', 169)
         , ('mi_request_to_cancel_date', 'String', NULL, -1, -1, 'none', 170)
         , ('pmi_cancellation_reason_code', 'String', NULL, -1, -1, 'none', 171)
         , ('pmi_cancellation_reason_code_description', 'String', NULL, -1, -1, 'none', 172)
         , ('va_loan_number', 'String', NULL, -1, -1, 'none', 173)
         , ('va_lin_check_digit_number', 'String', NULL, -1, -1, 'none', 174)
         , ('recover_corp_advance_balance', 'String', NULL, -1, -1, 'none', 175)
         , ('third_party_recoverable_ca_bal', 'String', NULL, -1, -1, 'none', 176)
         , ('non_rec_corp_advance_balance', 'String', NULL, -1, -1, 'none', 177)
         , ('second_principal_balance', 'String', NULL, -1, -1, 'none', 178)
         , ('actual_deferred_balance', 'String', NULL, -1, -1, 'none', 179)
         , ('ytd_principal_paid_amount', 'String', NULL, -1, -1, 'none', 180)
         , ('ytd_interest_amount', 'String', NULL, -1, -1, 'none', 181)
         , ('ytd_tax_amount', 'String', NULL, -1, -1, 'none', 182)
         , ('ytd_ioe_amount', 'String', NULL, -1, -1, 'none', 183)
         , ('ytd_hazard_amt', 'String', NULL, -1, -1, 'none', 184)
         , ('ytd_lien_amount', 'String', NULL, -1, -1, 'none', 185)
         , ('ytd_mip_amount', 'String', NULL, -1, -1, 'none', 186)
         , ('ytd_nsf_total', 'String', NULL, -1, -1, 'none', 187)
         , ('ytd_restricted_ioe_amount', 'String', NULL, -1, -1, 'none', 188)
         , ('ytd_late_charge_amount', 'String', NULL, -1, -1, 'none', 189)
         , ('prepay_penalty_indicator', 'String', NULL, -1, -1, 'none', 190)
         , ('ppp_header_id', 'String', NULL, -1, -1, 'none', 191)
         , ('ppp_header_name', 'String', NULL, -1, -1, 'none', 192)
         , ('user_05_position_field_2a', 'String', NULL, -1, -1, 'none', 193)
         , ('purchase_price', 'String', NULL, -1, -1, 'none', 194)
         , ('interest_calc_option_code', 'String', NULL, -1, -1, 'none', 195)
         , ('the_360_365_factor', 'String', NULL, -1, -1, 'none', 196)
         , ('the_360_365_factor_description', 'String', NULL, -1, -1, 'none', 197)
         , ('assumption_code', 'String', NULL, -1, -1, 'none', 198)
         , ('assumption_code_description', 'String', NULL, -1, -1, 'none', 199)
         , ('bill_code', 'String', NULL, -1, -1, 'none', 200)
         , ('bill_code_description', 'String', NULL, -1, -1, 'none', 201)
         , ('rhs_borrower_id', 'String', NULL, -1, -1, 'none', 202)
         , ('opt_ins_plan_id', 'String', NULL, -1, -1, 'none', 203)
         , ('certificate_number_1', 'String', NULL, -1, -1, 'none', 204)
         , ('certificate_number_2', 'String', NULL, -1, -1, 'none', 205)
         , ('opt_ins_disbursement_amount', 'String', NULL, -1, -1, 'none', 206)
         , ('opt_ins_disbursement_due_date', 'String', NULL, -1, -1, 'none', 207)
         , ('imminent_default_fico_score', 'String', NULL, -1, -1, 'none', 208)
         , ('imminent_default_fico_date', 'String', NULL, -1, -1, 'none', 209)
         , ('points_paid_by_borrower', 'String', NULL, -1, -1, 'none', 210)
         , ('third_party_draft_code', 'String', NULL, -1, -1, 'none', 211)
         , ('third_party_draft_code_description', 'String', NULL, -1, -1, 'none', 212)
         , ('employee_code', 'String', NULL, -1, -1, 'none', 213)
         , ('zone', 'String', NULL, -1, -1, 'none', 214)
         , ('sec_mortgagor_birth_date', 'String', NULL, -1, -1, 'none', 215)
         , ('sec_co_mortgagor_birth_date', 'String', NULL, -1, -1, 'none', 216)
         , ('email_address', 'String', NULL, -1, -1, 'none', 217)
         , ('co_mortgagor_email_address', 'String', NULL, -1, -1, 'none', 218)
         , ('servicing_sold_id', 'String', NULL, -1, -1, 'none', 219))

    , cte_csv_file_input_field as (INSERT INTO mdi.csv_file_input_field (csv_file_input_step_dwid, field_name, field_type, field_format, field_length, field_precision, field_trim_type, field_order)
        SELECT
              cte_csv_file_input_step.dwid
            , cte_csv_file_input_field_list.field_name
            , cte_csv_file_input_field_list.field_type::mdi.pentaho_field_type
            , cte_csv_file_input_field_list.field_format
            , cte_csv_file_input_field_list.field_length
            , cte_csv_file_input_field_list.field_precision
            , cte_csv_file_input_field_list.field_trim_type::mdi.pentaho_trim_type
            , cte_csv_file_input_field_list.field_order
        FROM
            cte_csv_file_input_field_list
            , cte_csv_file_input_step)

    , cte_table_output_step_values (target_schema, target_table, commit_size, partitioning_field, table_name_field, auto_generated_key_field, partition_data_per, table_name_defined_in_field, return_auto_generated_key_field, truncate_table, connectionname, partition_over_tables, specify_database_fields, ignore_insert_errors, use_batch_update) AS (
        VALUES ('dmi', 'passport', 1000, NULL, NULL, NULL, NULL, 'N', NULL, 'Y', 'Ingress DB Connection', 'N', 'Y', 'N', 'N'))

    , cte_table_output_step as (INSERT INTO mdi.table_output_step (process_dwid, target_schema, target_table, commit_size, partitioning_field, table_name_field, auto_generated_key_field, partition_data_per, table_name_defined_in_field, return_auto_generated_key_field, truncate_table, connectionname, partition_over_tables, specify_database_fields, ignore_insert_errors, use_batch_update)
        SELECT
              cte_process.dwid,
            cte_table_output_step_values.target_schema,
            cte_table_output_step_values.target_table,
            cte_table_output_step_values.commit_size,
            cte_table_output_step_values.partitioning_field,
            cte_table_output_step_values.table_name_field,
            cte_table_output_step_values.auto_generated_key_field,
            cte_table_output_step_values.partition_data_per,
            cte_table_output_step_values.table_name_defined_in_field::mdi.pentaho_y_or_n,
            cte_table_output_step_values.return_auto_generated_key_field,
            cte_table_output_step_values.truncate_table::mdi.pentaho_y_or_n,
            cte_table_output_step_values.connectionname,
            cte_table_output_step_values.partition_over_tables::mdi.pentaho_y_or_n,
            cte_table_output_step_values.specify_database_fields::mdi.pentaho_y_or_n,
            cte_table_output_step_values.ignore_insert_errors::mdi.pentaho_y_or_n,
            cte_table_output_step_values.use_batch_update::mdi.pentaho_y_or_n
        FROM
            cte_process
            , cte_table_output_step_values
        RETURNING dwid)


    , cte_table_output_field_list (database_field_name, database_stream_name, field_order, is_sensitive) as (
    VALUES ('loan_number', 'loan_number', 1, FALSE)
         , ('old_loan_number', 'old_loan_number', 2, FALSE)
         , ('new_servicer_loan_number', 'new_servicer_loan_number', 3, FALSE)
         , ('user_03_position_field_3a', 'user_03_position_field_3a', 4, FALSE)
         , ('first_due_date', 'first_due_date', 5, FALSE)
         , ('loan_closing_date', 'loan_closing_date', 6, FALSE)
         , ('loan_purpose_code', 'loan_purpose_code', 7, FALSE)
         , ('loan_purpose_code_description', 'loan_purpose_code_description', 8, FALSE)
         , ('note_date', 'note_date', 9, FALSE)
         , ('acquisition_date', 'acquisition_date', 10, FALSE)
         , ('original_interest_rate', 'original_interest_rate', 11, FALSE)
         , ('original_loan_term', 'original_loan_term', 12, FALSE)
         , ('original_mortgage_amount', 'original_mortgage_amount', 13, FALSE)
         , ('original_p_and_i_amount', 'original_p_and_i_amount', 14, FALSE)
         , ('original_property_value_amount', 'original_property_value_amount', 15, FALSE)
         , ('original_second_interest_rate', 'original_second_interest_rate', 16, FALSE)
         , ('original_second_loan_term', 'original_second_loan_term', 17, FALSE)
         , ('original_second_mtg_amount', 'original_second_mtg_amount', 18, FALSE)
         , ('original_second_p_and_i', 'original_second_p_and_i', 19, FALSE)
         , ('original_loan_to_value_ratio', 'original_loan_to_value_ratio', 20, FALSE)
         , ('annual_interest_rate', 'annual_interest_rate', 21, FALSE)
         , ('arm_indicator', 'arm_indicator', 22, FALSE)
         , ('drafting_indicator', 'drafting_indicator', 23, FALSE)
         , ('draft_option_code', 'draft_option_code', 24, FALSE)
         , ('draft_delay_days_quantity', 'draft_delay_days_quantity', 25, FALSE)
         , ('billing_mode', 'billing_mode', 26, FALSE)
         , ('coupon_tape_date', 'coupon_tape_date', 27, FALSE)
         , ('coupon_bill_last_create_date', 'coupon_bill_last_create_date', 28, FALSE)
         , ('def_int_balance', 'def_int_balance', 29, FALSE)
         , ('distribution_type', 'distribution_type', 30, FALSE)
         , ('loan_to_value_ratio', 'loan_to_value_ratio', 31, FALSE)
         , ('first_p_and_i_amount', 'first_p_and_i_amount', 32, FALSE)
         , ('first_principal_balance', 'first_principal_balance', 33, FALSE)
         , ('el_status_indicator', 'el_status_indicator', 34, FALSE)
         , ('interest_only_expire_date', 'interest_only_expire_date', 35, FALSE)
         , ('interest_only_loan_indicator', 'interest_only_loan_indicator', 36, FALSE)
         , ('qualified_mortgage_code', 'qualified_mortgage_code', 37, FALSE)
         , ('qualified_mortgage_code_description', 'qualified_mortgage_code_description', 38, FALSE)
         , ('higher_priced_indicator', 'higher_priced_indicator', 39, FALSE)
         , ('higher_priced_indicator_description', 'higher_priced_indicator_description', 40, FALSE)
         , ('high_cost_type', 'high_cost_type', 41, FALSE)
         , ('high_cost_type_description', 'high_cost_type_description', 42, FALSE)
         , ('escrow_waiver_code', 'escrow_waiver_code', 43, FALSE)
         , ('escrow_waiver_code_description', 'escrow_waiver_code_description', 44, FALSE)
         , ('escrow_waiver_date', 'escrow_waiver_date', 45, FALSE)
         , ('investor_loan_number', 'investor_loan_number', 46, FALSE)
         , ('investor_id', 'investor_id', 47, FALSE)
         , ('category_code', 'category_code', 48, FALSE)
         , ('first_service_fee_rate', 'first_service_fee_rate', 49, FALSE)
         , ('pool_number', 'pool_number', 50, FALSE)
         , ('pool_class_code', 'pool_class_code', 51, FALSE)
         , ('pool_contract_number', 'pool_contract_number', 52, FALSE)
         , ('gse_code', 'gse_code', 53, FALSE)
         , ('gse_code_description', 'gse_code_description', 54, FALSE)
         , ('hi_type', 'hi_type', 55, FALSE)
         , ('hi_type_description', 'hi_type_description', 56, FALSE)
         , ('lo_type', 'lo_type', 57, FALSE)
         , ('lo_type_description', 'lo_type_description', 58, FALSE)
         , ('development_type', 'development_type', 59, FALSE)
         , ('development_type_description', 'development_type_description', 60, FALSE)
         , ('second_hi_type', 'second_hi_type', 61, FALSE)
         , ('bl_balloon_status_code', 'bl_balloon_status_code', 62, FALSE)
         , ('bl_balloon_status_code_description', 'bl_balloon_status_code_description', 63, FALSE)
         , ('balloon_status_code', 'balloon_status_code', 64, FALSE)
         , ('balloon_status_code_description', 'balloon_status_code_description', 65, FALSE)
         , ('loan_matures_date', 'loan_matures_date', 66, FALSE)
         , ('loan_term', 'loan_term', 67, FALSE)
         , ('remaining_term', 'remaining_term', 68, FALSE)
         , ('man_code', 'man_code', 69, FALSE)
         , ('man_code_description', 'man_code_description', 70, FALSE)
         , ('mers_id', 'mers_id', 71, FALSE)
         , ('mers_original_mortgagee_ind', 'mers_original_mortgagee_ind', 72, FALSE)
         , ('mers_original_mortgagee_ind_description', 'mers_original_mortgagee_ind_description', 73, FALSE)
         , ('mers_registration_status_code', 'mers_registration_status_code', 74, FALSE)
         , ('mers_registration_date', 'mers_registration_date', 75, FALSE)
         , ('mers_id_number_status_code', 'mers_id_number_status_code', 76, FALSE)
         , ('mers_assigned_date', 'mers_assigned_date', 77, FALSE)
         , ('next_payment_due_date', 'next_payment_due_date', 78, FALSE)
         , ('last_full_payment_date', 'last_full_payment_date', 79, FALSE)
         , ('due_date_day_portion_parsed', 'due_date_day_portion_parsed', 80, FALSE)
         , ('payment_period', 'payment_period', 81, FALSE)
         , ('payment_option_code', 'payment_option_code', 82, FALSE)
         , ('payment_option_code_description', 'payment_option_code_description', 83, FALSE)
         , ('suspense_balance', 'suspense_balance', 84, FALSE)
         , ('nsf_fee_balance', 'nsf_fee_balance', 85, FALSE)
         , ('total_monthly_payment', 'total_monthly_payment', 86, FALSE)
         , ('billing_name', 'billing_name', 87, FALSE)
         , ('billing_address_line_2', 'billing_address_line_2', 88, FALSE)
         , ('co_mortgagor_name', 'co_mortgagor_name', 89, FALSE)
         , ('billing_address_line_3', 'billing_address_line_3', 90, FALSE)
         , ('billing_address_line_4', 'billing_address_line_4', 91, FALSE)
         , ('billing_city_name', 'billing_city_name', 92, FALSE)
         , ('foreign_address_indicator', 'foreign_address_indicator', 93, FALSE)
         , ('billing_state', 'billing_state', 94, FALSE)
         , ('billing_zip_code', 'billing_zip_code', 95, FALSE)
         , ('telephone_number', 'telephone_number', 96, FALSE)
         , ('telephone_code', 'telephone_code', 97, FALSE)
         , ('mortgagor_prefered_lang_code', 'mortgagor_prefered_lang_code', 98, FALSE)
         , ('second_telephone_number', 'second_telephone_number', 99, FALSE)
         , ('sec_mortgagor_ss_number', 'sec_mortgagor_ss_number', 100, FALSE)
         , ('sec_co_mortgagor_ss_number', 'sec_co_mortgagor_ss_number', 101, FALSE)
         , ('property_street_address', 'property_street_address', 102, FALSE)
         , ('property_unit_number', 'property_unit_number', 103, FALSE)
         , ('city_name', 'city_name', 104, FALSE)
         , ('property_alpha_state_code', 'property_alpha_state_code', 105, FALSE)
         , ('property_zip_code', 'property_zip_code', 106, FALSE)
         , ('county_code', 'county_code', 107, FALSE)
         , ('fips_county_code', 'fips_county_code', 108, FALSE)
         , ('fips_state_code', 'fips_state_code', 109, FALSE)
         , ('occupancy_code', 'occupancy_code', 110, FALSE)
         , ('occupancy_code_description', 'occupancy_code_description', 111, FALSE)
         , ('property_state_code', 'property_state_code', 112, FALSE)
         , ('number_of_units', 'number_of_units', 113, FALSE)
         , ('appraisal_date', 'appraisal_date', 114, FALSE)
         , ('property_value_amount', 'property_value_amount', 115, FALSE)
         , ('property_type', 'property_type', 116, FALSE)
         , ('property_type_fnma_code', 'property_type_fnma_code', 117, FALSE)
         , ('property_type_fnma_code_description', 'property_type_fnma_code_description', 118, FALSE)
         , ('occupancy_current_status_code', 'occupancy_current_status_code', 119, FALSE)
         , ('occupancy_current_status_code_description', 'occupancy_current_status_code_description', 120, FALSE)
         , ('ownership_type', 'ownership_type', 121, FALSE)
         , ('ownership_type_description', 'ownership_type_description', 122, FALSE)
         , ('flood_community_start_date', 'flood_community_start_date', 123, FALSE)
         , ('flood_program_type', 'flood_program_type', 124, FALSE)
         , ('flood_loma_revision_code', 'flood_loma_revision_code', 125, FALSE)
         , ('flood_loma_determination_date', 'flood_loma_determination_date', 126, FALSE)
         , ('flood_contract_type', 'flood_contract_type', 127, FALSE)
         , ('flood_community_number', 'flood_community_number', 128, FALSE)
         , ('flood_panel_number', 'flood_panel_number', 129, FALSE)
         , ('flood_zone_position_1', 'flood_zone_position_1', 130, FALSE)
         , ('flood_zone_position_2_and_3', 'flood_zone_position_2_and_3', 131, FALSE)
         , ('flood_suffix_number', 'flood_suffix_number', 132, FALSE)
         , ('flood_zone_partial_indicator', 'flood_zone_partial_indicator', 133, FALSE)
         , ('flood_firm_effective_date', 'flood_firm_effective_date', 134, FALSE)
         , ('flood_mapping_company_id', 'flood_mapping_company_id', 135, FALSE)
         , ('flood_certification_number', 'flood_certification_number', 136, FALSE)
         , ('grace_days', 'grace_days', 137, FALSE)
         , ('late_charge_amount', 'late_charge_amount', 138, FALSE)
         , ('late_charge_code', 'late_charge_code', 139, FALSE)
         , ('late_charge_code_description', 'late_charge_code_description', 140, FALSE)
         , ('late_charge_factor', 'late_charge_factor', 141, FALSE)
         , ('maximum_late_charge_amount', 'maximum_late_charge_amount', 142, FALSE)
         , ('minimum_late_charge_amount', 'minimum_late_charge_amount', 143, FALSE)
         , ('delinquency_class_code', 'delinquency_class_code', 144, FALSE)
         , ('delinquency_class_code_description', 'delinquency_class_code_description', 145, FALSE)
         , ('secondary_phone_code', 'secondary_phone_code', 146, FALSE)
         , ('secondary_phone_number', 'secondary_phone_number', 147, FALSE)
         , ('escrow_advance_balance', 'escrow_advance_balance', 148, FALSE)
         , ('escrow_balance', 'escrow_balance', 149, FALSE)
         , ('escrow_replace_resrv_balance', 'escrow_replace_resrv_balance', 150, FALSE)
         , ('hazard_ins_monthly_amount', 'hazard_ins_monthly_amount', 151, FALSE)
         , ('replace_reserve_amount', 'replace_reserve_amount', 152, FALSE)
         , ('restricted_escrow_balance', 'restricted_escrow_balance', 153, FALSE)
         , ('t_and_i_monthly_amount', 't_and_i_monthly_amount', 154, FALSE)
         , ('a_and_h_premium_amount', 'a_and_h_premium_amount', 155, FALSE)
         , ('life_premium_amount', 'life_premium_amount', 156, FALSE)
         , ('interest_paid_through_date', 'interest_paid_through_date', 157, FALSE)
         , ('ln_mod_code', 'ln_mod_code', 158, FALSE)
         , ('ln_mod_code_description', 'ln_mod_code_description', 159, FALSE)
         , ('last_analysis_date', 'last_analysis_date', 160, FALSE)
         , ('last_analysis_effective_date', 'last_analysis_effective_date', 161, FALSE)
         , ('last_analysis_os_spread_months', 'last_analysis_os_spread_months', 162, FALSE)
         , ('mi_monthly_amount', 'mi_monthly_amount', 163, FALSE)
         , ('mi_term', 'mi_term', 164, FALSE)
         , ('mi_disbursement_amount', 'mi_disbursement_amount', 165, FALSE)
         , ('mi_disbursement_due_date', 'mi_disbursement_due_date', 166, FALSE)
         , ('mi_mid_point_date', 'mi_mid_point_date', 167, FALSE)
         , ('mi_termination_date', 'mi_termination_date', 168, FALSE)
         , ('mi_cancellation_date', 'mi_cancellation_date', 169, FALSE)
         , ('mi_request_to_cancel_date', 'mi_request_to_cancel_date', 170, FALSE)
         , ('pmi_cancellation_reason_code', 'pmi_cancellation_reason_code', 171, FALSE)
         , ('pmi_cancellation_reason_code_description', 'pmi_cancellation_reason_code_description', 172, FALSE)
         , ('va_loan_number', 'va_loan_number', 173, FALSE)
         , ('va_lin_check_digit_number', 'va_lin_check_digit_number', 174, FALSE)
         , ('recover_corp_advance_balance', 'recover_corp_advance_balance', 175, FALSE)
         , ('third_party_recoverable_ca_bal', 'third_party_recoverable_ca_bal', 176, FALSE)
         , ('non_rec_corp_advance_balance', 'non_rec_corp_advance_balance', 177, FALSE)
         , ('second_principal_balance', 'second_principal_balance', 178, FALSE)
         , ('actual_deferred_balance', 'actual_deferred_balance', 179, FALSE)
         , ('ytd_principal_paid_amount', 'ytd_principal_paid_amount', 180, FALSE)
         , ('ytd_interest_amount', 'ytd_interest_amount', 181, FALSE)
         , ('ytd_tax_amount', 'ytd_tax_amount', 182, FALSE)
         , ('ytd_ioe_amount', 'ytd_ioe_amount', 183, FALSE)
         , ('ytd_hazard_amt', 'ytd_hazard_amt', 184, FALSE)
         , ('ytd_lien_amount', 'ytd_lien_amount', 185, FALSE)
         , ('ytd_mip_amount', 'ytd_mip_amount', 186, FALSE)
         , ('ytd_nsf_total', 'ytd_nsf_total', 187, FALSE)
         , ('ytd_restricted_ioe_amount', 'ytd_restricted_ioe_amount', 188, FALSE)
         , ('ytd_late_charge_amount', 'ytd_late_charge_amount', 189, FALSE)
         , ('prepay_penalty_indicator', 'prepay_penalty_indicator', 190, FALSE)
         , ('ppp_header_id', 'ppp_header_id', 191, FALSE)
         , ('ppp_header_name', 'ppp_header_name', 192, FALSE)
         , ('user_05_position_field_2a', 'user_05_position_field_2a', 193, FALSE)
         , ('purchase_price', 'purchase_price', 194, FALSE)
         , ('interest_calc_option_code', 'interest_calc_option_code', 195, FALSE)
         , ('the_360_365_factor', 'the_360_365_factor', 196, FALSE)
         , ('the_360_365_factor_description', 'the_360_365_factor_description', 197, FALSE)
         , ('assumption_code', 'assumption_code', 198, FALSE)
         , ('assumption_code_description', 'assumption_code_description', 199, FALSE)
         , ('bill_code', 'bill_code', 200, FALSE)
         , ('bill_code_description', 'bill_code_description', 201, FALSE)
         , ('rhs_borrower_id', 'rhs_borrower_id', 202, FALSE)
         , ('opt_ins_plan_id', 'opt_ins_plan_id', 203, FALSE)
         , ('certificate_number_1', 'certificate_number_1', 204, FALSE)
         , ('certificate_number_2', 'certificate_number_2', 205, FALSE)
         , ('opt_ins_disbursement_amount', 'opt_ins_disbursement_amount', 206, FALSE)
         , ('opt_ins_disbursement_due_date', 'opt_ins_disbursement_due_date', 207, FALSE)
         , ('imminent_default_fico_score', 'imminent_default_fico_score', 208, FALSE)
         , ('imminent_default_fico_date', 'imminent_default_fico_date', 209, FALSE)
         , ('points_paid_by_borrower', 'points_paid_by_borrower', 210, FALSE)
         , ('third_party_draft_code', 'third_party_draft_code', 211, FALSE)
         , ('third_party_draft_code_description', 'third_party_draft_code_description', 212, FALSE)
         , ('employee_code', 'employee_code', 213, FALSE)
         , ('zone', 'zone', 214, FALSE)
         , ('sec_mortgagor_birth_date', 'sec_mortgagor_birth_date', 215, FALSE)
         , ('sec_co_mortgagor_birth_date', 'sec_co_mortgagor_birth_date', 216, FALSE)
         , ('email_address', 'email_address', 217, FALSE)
         , ('co_mortgagor_email_address', 'co_mortgagor_email_address', 218, FALSE)
         , ('servicing_sold_id', 'servicing_sold_id', 219, FALSE)
         , ('etl_batch_id', 'etl_batch_id', 220, FALSE)
         , ('data_source_dwid', 'data_source_dwid', 221, FALSE)
         , ('input_filename', 'imported_filename', 222, FALSE))

   , cte_table_output_field as (INSERT INTO mdi.table_output_field (table_output_step_dwid, database_field_name, database_stream_name, field_order, is_sensitive)
           SELECT
               cte_table_output_step.dwid
               , cte_table_output_field_list.database_field_name
               , cte_table_output_field_list.database_stream_name
               , cte_table_output_field_list.field_order
               , cte_table_output_field_list.is_sensitive
           FROM
               cte_table_output_field_list
               , cte_table_output_step
    )
    select cte_table_output_step.dwid FROM cte_table_output_step;

SELECT 'Done adding MDI configuration for dmi.passport (SP-7)' as etl_creator_status;
