-------------------------------------------------------------------------------
--  NAME
--      Add Raw Encompass Tables
--
--  ASANA
--      https://app.asana.com/0/265828915819547/1170641800406346
--      https://app.asana.com/0/265828915819547/1163456485468342
--      https://app.asana.com/0/265828915819547/1170641800406346
--      https://app.asana.com/0/265828915819547/1166527173409791
--      https://app.asana.com/0/265828915819547/1174838407509437
--
--  DESCRIPTION/PURPOSE
--      This script adds the tables that are needed to load Encompass loan data
--      into the Enterprise Data Warehouse (EDW).
--
-- PROGRAMMING NOTES
--      Tables encompass.encompass_loan_raw and encompass_encompass_loan_raw_error
--      have functions associated with them to auto populate the created_at and
--      updated_at columns. A trigger updates the updated_at column when it is modified
--      so we can easily tell if any data was modified after the initial load.
--
-------------------------------------------------------------------------------


-- Function: set_timestamp
CREATE OR REPLACE FUNCTION encompass.set_timestamp()
	RETURNS TRIGGER AS
$$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- Table: encompass.encompass_loan_raw
CREATE TABLE encompass.encompass_loan_raw
(
	created_at TIMESTAMP                      NOT NULL DEFAULT now(),
	updated_at TIMESTAMP                      NOT NULL DEFAULT now(),
	elr_trans_details_loan_number BIGINT      NOT NULL,
	elr_loan_info_loan_id TEXT,
	elr_loan_info_loan_created_date TIMESTAMP NOT NULL,
	elr_loan_officer_lead_id TEXT,
	elr_loan_officer_lead_source TEXT,
	elr_loan_officer_lead_source_reference_id TEXT,
	elr_borrower_intends_to_continue_chkbx BOOLEAN,
	elr_trans_details_lien_position TEXT,
	elr_trans_details_loan_amt NUMERIC(17, 2),
	elr_trans_details_interest_rate NUMERIC(20, 9),
	elr_trans_details_loan_purpose TEXT,
	elr_loan_info_refi_purpose TEXT,
	elr_trans_details_loan_program TEXT,
	elr_trans_details_down_pmt_percent NUMERIC(20, 9),
	elr_trans_details_qual_ratio_top NUMERIC(20, 9),
	elr_trans_details_qual_ratio_bottom NUMERIC(20, 9),
	elr_fannie_mae_loan_doc_type_code TEXT,
	elr_trans_details_purchase_price NUMERIC(17, 2),
	elr_trans_details_comb_loan_to_value_cltv NUMERIC(20, 9),
	elr_trans_details_apr NUMERIC(20, 9),
	elr_trans_details_term_mos INTEGER,
	elr_trans_details_interest_only_indicator BOOLEAN,
	elr_prepayment_penalty BOOLEAN,
	elr_mlds_prepymt_penalty_period NUMERIC(20, 9),
	elr_trans_details_amort_type TEXT,
	elr_sebonic_custom_impound_field TEXT,
	elr_borrower_first_name TEXT,
	elr_borrower_middle_name TEXT,
	elr_borrower_last_name TEXT,
	elr_borr_email TEXT,
	elr_borr_home_phone TEXT,
	elr_borr_business_phone TEXT,
	elr_borr_cell TEXT,
	elr_borr_present_addr TEXT,
	elr_borr_present_city TEXT,
	elr_borr_present_state TEXT,
	elr_borr_present_zip TEXT,
	elr_borr_dob TIMESTAMP,
	elr_borr_sex_male_female TEXT,
	elr_borr_ethnicity TEXT,
	elr_borr_race_american_indian BOOLEAN,
	elr_borr_race_asian BOOLEAN,
	elr_borr_race_black BOOLEAN,
	elr_borr_race_native_hawaiian BOOLEAN,
	elr_borr_race_white BOOLEAN,
	elr_borr_race_info_not_provided BOOLEAN,
	elr_borr_race_not_applicable BOOLEAN,
	elr_borr_first_time_homebuyer BOOLEAN,
	elr_borr_self_employed BOOLEAN,
	elr_income_borr_total_income NUMERIC(17, 2),
	elr_financed_property_ownership_count INTEGER,
	elr_borr_lmedian_fico INTEGER,
	elr_coborr_lmedian_fico INTEGER,
	elr_va_loan_summ_credit_score INTEGER,
	elr_coborrower_first_name TEXT,
	elr_coborrower_middle_name TEXT,
	elr_coborrower_last_name TEXT,
	elr_coborr_email TEXT,
	elr_coborr_home_phone TEXT,
	elr_coborr_business_phone TEXT,
	elr_coborr_cell TEXT,
	elr_coborr_present_addr TEXT,
	elr_coborr_present_city TEXT,
	elr_coborr_present_state TEXT,
	elr_coborr_present_zip TEXT,
	elr_coborr_dob TIMESTAMP,
	elr_coborr_sex_male_female TEXT,
	elr_coborr_experian_fico INTEGER,
	elr_coborr_ethnicity TEXT,
	elr_coborr_race_american_indian BOOLEAN,
	elr_coborr_race_asian BOOLEAN,
	elr_coborr_race_black BOOLEAN,
	elr_coborr_race_native_hawaiian BOOLEAN,
	elr_coborr_race_white BOOLEAN,
	elr_coborr_race_info_not_provided BOOLEAN,
	elr_coborr_race_not_applicable BOOLEAN,
	elr_income_verification_available_b1 BOOLEAN,
	elr_income_verification_available_c1 BOOLEAN,
	elr_subject_property_type TEXT,
	elr_subject_property_occupancy_status TEXT,
	elr_subject_property_street TEXT,
	elr_subject_property_street_2 TEXT,
	elr_subject_property_city TEXT,
	elr_subject_property_state TEXT,
	elr_subject_property_zip TEXT,
	elr_subject_property_county TEXT,
	elr_subject_property_msa_number TEXT,
	elr_subject_property_county_code TEXT,
	elr_subject_property_number_units INTEGER,
	elr_subject_property_yr_built TEXT,
	elr_subject_property_est_value NUMERIC(17, 2),
	elr_subject_property_appraised_value NUMERIC(17, 2),
	elr_subject_property_estate_held TEXT,
	elr_occupancy_type TEXT,
	elr_property_type TEXT,
	elr_document_date_received_credit_report TIMESTAMP,
	elr_trans_details_credit_rpt_ref_number TEXT,
	elr_payoff_junior_lien_holder_company TEXT,
	elr_payoff_primary_lien_holder_company TEXT,
	elr_appraisal_retrieval_relative_value TEXT,
	elr_appraisal_report_asis TEXT,
	elr_lo_compensation_fee_line_802_discount_point_percent_line_2 NUMERIC(20, 9),
	elr_lo_compensation_fee_line_802_discount_point_percent_line_4 NUMERIC(20, 9),
	elr_lo_compensation_fee_line_802_user_defined_fee_2_amount NUMERIC(17, 2),
	elr_fees_line_801_borr_paid_orig_chrg NUMERIC(17, 2),
	elr_fees_line_801_user_defined_fee_2_borr_amt NUMERIC(17, 2),
	elr_fees_line_801_broker_compensation_borrower_paid NUMERIC(17, 2),
	elr_fees_line_801_user_defined_fee_2_descr TEXT,
	elr_fees_line_802_borr_credit_points NUMERIC(17, 2),
	elr_fees_line_803_borr_paid_adj_orig_chrgs NUMERIC(17, 2),
	elr_fees_loan_origination_fee_borr NUMERIC(17, 2),
	elr_fees_orig_charge_amt_borr NUMERIC(17, 2),
	elr_fees_compensation_to_broker_1 NUMERIC(17, 2),
	elr_lo_compensation_lender_compensation_credit_amount_line_2 NUMERIC(17, 2),
	elr_lo_compensation_borrower_paid_discount_point_amount_line_3 NUMERIC(17, 2),
	elr_requested_lo_concession_amount NUMERIC(17, 2),
	elr_loan_officer_manager_concession_amount NUMERIC(17, 2),
	elr_lo_compensation_borrower_paid_discount_point_amount_line_1 NUMERIC(17, 2),
	elr_total_credit_for_rate_chosen NUMERIC(17, 2),
	elr_lo_compensation_totalborrower_discount_point_amount_line_4 NUMERIC(17, 2),
	elr_hud1_borr_paid_by_for_borr_oth_1_amt NUMERIC(17, 2),
	elr_fees_line_801_user_def_fee_1_borr NUMERIC(17, 2),
	elr_disclosed_fees_total_finance_charges NUMERIC(17, 2),
	elr_document_date_received_loan_officer_preapproval_letter TIMESTAMP,
	elr_underwriting_risk_assess_type TEXT,
	elr_underwriting_suspended_date TIMESTAMP,
	elr_underwriting_level_of_prpty_review_form_number TEXT,
	elr_uw_suspended_cleared_date TIMESTAMP,
	elr_credit_committee_fico_exception BOOLEAN,
	elr_fnma_cu_risk_score NUMERIC(20, 9),
	elr_day_1_income_verification_available BOOLEAN,
	elr_du_fail_reason TEXT,
	elr_acceptable_du TEXT,
	elr_acceptable_lp TEXT,
	elr_atr_qm_eligibility_abilitytorepay_loan_type TEXT,
	elr_rate_lock_request_fulfilled_date_time_most_recent TIMESTAMP,
	elr_rate_lock_request_fulfilled_date_time TIMESTAMP,
	elr_rate_lock_trans_details_loan_program_most_recent TEXT,
	elr_rate_lock_lock_request_loan_type_most_recent TEXT,
	elr_rate_lock_buy_side_base_margin NUMERIC(20, 9),
	elr_lock_request_loan_amnt_excluding_mip_pmi_most_recent NUMERIC(17, 2),
	elr_lock_request_subject_property_number_units_most_recent INTEGER,
	elr_rate_lock_buy_side_lock_expires_date TIMESTAMP,
	elr_rate_lock_buy_side_lock_date TIMESTAMP,
	elr_first_lock_lock_date TIMESTAMP,
	elr_rate_lock_lock_request_impounds_waived_most_recent NUMERIC(17, 2),
	elr_rate_lock_lock_request_loan_amount_most_recent NUMERIC(17, 2),
	elr_rate_lock_trans_details_amort_type_most_recent TEXT,
	elr_rate_lock_request_rate_sheet_id TEXT,
	elr_rate_lock_buy_side_investor_commitment TEXT,
	elr_rate_lock_buy_side_comments TEXT,
	elr_rate_lock_sell_side_lock_expires_date TIMESTAMP,
	elr_rate_lock_sell_side_number_of_days INTEGER,
	elr_rate_lock_sell_side_total_sell_price NUMERIC(17, 2),
	elr_rate_lock_sell_side_investor_lock_type TEXT,
	elr_rate_lock_sell_investor_name TEXT,
	elr_rate_lock_sell_side_investor_loan_number TEXT,
	elr_rate_lock_sell_side_lock_date TIMESTAMP,
	elr_rate_lock_sell_side_lock_date_most_recent TIMESTAMP,
	elr_rate_lock_sell_side_base_rate NUMERIC(20, 9),
	elr_rate_lock_sell_side_investor_delivery_date TIMESTAMP,
	elr_rate_lock_sell_side_base_rate_adjust_1_rate_most_recent NUMERIC(20, 9),
	elr_rate_lock_sell_side_investor_commitment_most_recent TEXT,
	elr_rate_lock_sell_side_net_sell_price NUMERIC(17, 2),
	elr_rate_lock_sell_side_net_buy_rate NUMERIC(20, 9),
	elr_rate_lock_trans_details_term_mos_most_recent INTEGER,
	elr_rate_lock_buy_side_number_of_days INTEGER,
	elr_first_lock_ltv NUMERIC(20, 9),
	elr_first_lock_cltv NUMERIC(20, 9),
	elr_first_lock_net_buy_price NUMERIC(17, 2),
	elr_trans_details_lock_date TIMESTAMP,
	elr_trans_details_rate_lock_expires TIMESTAMP,
	elr_trans_details_rate_lock_number_days INTEGER,
	elr_lock_extension_original_lock_term INTEGER,
	elr_lock_extension_original_lock_date TIMESTAMP,
	elr_lock_extension_original_lock_expiration_date TIMESTAMP,
	elr_lock_extension_new_expiration_date TIMESTAMP,
	elr_initial_capture_of_lock_number_days INTEGER,
	elr_trans_details_first_pymt_date TIMESTAMP,
	elr_trans_details_first_pymt_adj_date TIMESTAMP,
	elr_trans_details_loan_maturity_date TIMESTAMP,
	elr_trans_details_total_loan_amt_w_mip_ff NUMERIC(17, 2),
	elr_loan_info_arm_disclosure_type TEXT,
	elr_loan_info_arm_margin NUMERIC(20, 9),
	elr_freddie_mac_lender_rate_adj_convertible NUMERIC(20, 9),
	elr_freddie_mac_loan_to_value_ltv NUMERIC(20, 9),
	elr_regz_loan_info_document_date TIMESTAMP,
	elr_trans_details_loan_type TEXT,
	elr_trans_details_sub_fin_second_mtg_loan_amt NUMERIC(17, 2),
	elr_aus_eligibility_for_miac TEXT,
	elr_total_number_of_borrowers_on_loan INTEGER,
	elr_trans_details_mo_pymt_p_and_i NUMERIC(17, 2),
	elr_extension_cost_total_amount NUMERIC(17, 2),
	elr_homeready_eligibility BOOLEAN,
	elr_homeready_eligibility_review_complete BOOLEAN,
	elr_homeready_borrower_acceptance BOOLEAN,
	elr_homepossible_eligibility BOOLEAN,
	elr_homepossible_eligibility_review_complete BOOLEAN,
	elr_underwriting_investor_eligibility_fannie_mae BOOLEAN,
	elr_underwriting_investor_eligibility_freddie_mac BOOLEAN,
	elr_morgan_stanley_upload BOOLEAN,
	elr_loan_info_arm_first_period_change NUMERIC(20, 9),
	elr_loan_info_arm_first_rate_adj_cap NUMERIC(20, 9),
	elr_loan_info_arm_floor_rate NUMERIC(20, 9),
	elr_loan_info_arm_rate_adj_period NUMERIC(20, 9),
	elr_loan_info_arm_rate_cap NUMERIC(20, 9),
	elr_loan_info_arm_max_life_interest_cap NUMERIC(20, 9),
	elr_mi_company_name_type TEXT,
	elr_file_contacts_mtg_ins_co_name TEXT,
	elr_insurance_mtg_ins_coverage_factor NUMERIC(20, 9),
	elr_private_mortgage_insurance_indicator BOOLEAN,
	elr_uldd_mortgage_insurance_premium_source_type TEXT,
	elr_lpmi_estimated_amount_of_lender_paid_mi_premium NUMERIC(20, 9),
	elr_lpmi_final_price_of_lpmi NUMERIC(17, 2),
	elr_lo_workksheet_mi_premium_frequency TEXT,
	elr_file_contacts_mtg_ins_co_file_number TEXT,
	elr_document_date_received_postfunding_disbursement_ledger TIMESTAMP,
	elr_warehouse_curtailment BOOLEAN,
	elr_funding_executed_docs_in_date_time TEXT,
	elr_funding_funds_ordered_date TIMESTAMP,
	elr_funding_funds_sent_date TIMESTAMP,
	elr_funding_funds_released TIMESTAMP,
	elr_fund_outstanding_docs_funding_authorized BOOLEAN,
	elr_delivery_work_completed_checkbox BOOLEAN,
	elr_file_contacts_warehouse_co_name TEXT,
	elr_coll_to_warehouse_warehouse_company TEXT,
	elr_bb_and_t_elds_maturity TEXT,
	elr_intrm_serv_pymnt_summary_prncpl_balance NUMERIC(17, 2),
	elr_coll_delivery_dmi_id TEXT,
	elr_intrm_serv_next_pymnt_pymnt_due_date TIMESTAMP,
	elr_dmi_upload_p_and_i_change_date TIMESTAMP,
	elr_shipping_investor_delivery_date TIMESTAMP,
	elr_shipping_actual_shipping_date TIMESTAMP,
	elr_coll_delivery_cust_to_inv_ship_date TIMESTAMP,
	elr_coll_to_investor_work_completed_date_stamp TIMESTAMP,
	elr_coll_delivery_to_custodian_ship_date TIMESTAMP,
	elr_purchase_advice_date TIMESTAMP,
	elr_purchase_advice_actual_sell_price NUMERIC(17, 2),
	elr_purchase_advice_date_first_payment_to_investor TEXT,
	elr_purchase_advice_first_payment_to TEXT,
	elr_purchase_advice_actual_sell_side_srp NUMERIC(20, 9),
	elr_purchase_advice_payouts_1_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_2_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_3_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_4_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_5_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_6_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_7_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_8_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_9_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_10_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_11_amount NUMERIC(17, 2),
	elr_purchase_advice_payouts_12_amount NUMERIC(17, 2),
	elr_purchase_advice_premium NUMERIC(17, 2),
	elr_purchase_advice_srp_received NUMERIC(20, 9),
	elr_underwriting_investor_eligibility_texas_50a6_cashout BOOLEAN,
	elr_underwriting_investor_eligibility_wells_fargo BOOLEAN,
	elr_underwriting_investor_eligibility_chase_jp_morgan BOOLEAN,
	elr_shipping_mers_registration_date TIMESTAMP,
	elr_trans_details_mers_min_number TEXT,
	elr_rate_lock_sell_side_investor_mers_number_most_recent NUMERIC(20, 9),
	elr_uldd_pool_id TEXT,
	elr_uldd_property_valuation_effective_date TIMESTAMP,
	elr_uldd_first_unit_bedrooms INTEGER,
	elr_uldd_first_unit_subject_property_gross_rent NUMERIC(17, 2),
	elr_loan_estimate_le_date_issued TIMESTAMP,
	elr_appraisal_retrieval_work_completed_date_date TIMESTAMP,
	elr_tracking_current_milestone_name TEXT,
	elr_tracking_current_milestone_date TIMESTAMP,
	elr_application_milestone_date TIMESTAMP,
	elr_trans_details_current_status_date TIMESTAMP,
	elr_trans_details_current_loan_status TEXT,
	elr_underwriting_clear_to_close_date TIMESTAMP,
	elr_trans_details_est_closing_date TIMESTAMP,
	elr_closing_scheduled_date TIMESTAMP,
	elr_tracking_doc_signed_milestone_date TIMESTAMP,
	elr_cl_docs_delivered_date_stamp TIMESTAMP,
	elr_trans_details_total_wire_transfer NUMERIC(17, 2),
	elr_trans_details_closed_date TIMESTAMP,
	elr_closing_docs_regz_loan_info_disbursement_date TIMESTAMP,
	elr_loan_folder_name TEXT,
	elr_file_contacts_buyers_agent_name TEXT,
	elr_file_contacts_buyers_agent_contact_name TEXT,
	elr_file_contacts_buyers_agent_email TEXT,
	elr_file_contacts_loan_officer_name TEXT,
	elr_file_contacts_loan_processor_name TEXT,
	elr_loan_team_member_name_fd_funder TEXT,
	elr_loan_team_member_name_cl_document_fmls TEXT,
	elr_nmls_loan_originator_id TEXT,
	elr_processing_resub_worker_assigned_date_stamp TIMESTAMP,
	elr_loan_team_member_name_uw_conditions_fmls TEXT,
	elr_loan_team_member_name_uw_underwriter TEXT,
	elr_loan_officer_appraisal_onhold_estimated_release_date TIMESTAMP,
	elr_loan_officer_appraisal_onhold_date_time_stamp TIMESTAMP,
	elr_loan_officer_appraisal_cleared_date_time_stamp TIMESTAMP,
	elr_refinance_type TEXT,
	elr_trans_details_purchaser_type TEXT,
	elr_trans_details_hoepa_status TEXT,
	elr_loan_info_channel TEXT
);


-- Trigger: set_timestamp_on_encompass_loan_raw
CREATE TRIGGER set_timestamp_on_encompass_loan_raw
	BEFORE UPDATE
	ON encompass.encompass_loan_raw
	FOR EACH ROW
EXECUTE PROCEDURE encompass.set_timestamp();


-- Table: encompass.encompass_loan_raw_error
CREATE TABLE encompass.encompass_loan_raw_error
(
	elr_error_id BIGSERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT now(),
	updated_at TIMESTAMP NOT NULL DEFAULT now(),
	elr_pentaho_error_code TEXT,
	elr_pentaho_error_description TEXT,
	elr_pentaho_error_field TEXT,
	elr_pentaho_number_of_errors NUMERIC,
	elr_trans_details_loan_number TEXT,
	elr_loan_info_loan_id TEXT,
	elr_loan_info_loan_created_date TEXT,
	elr_loan_officer_lead_id TEXT,
	elr_loan_officer_lead_source TEXT,
	elr_loan_officer_lead_source_reference_id TEXT,
	elr_borrower_intends_to_continue_chkbx TEXT,
	elr_trans_details_lien_position TEXT,
	elr_trans_details_loan_amt TEXT,
	elr_trans_details_interest_rate TEXT,
	elr_trans_details_loan_purpose TEXT,
	elr_loan_info_refi_purpose TEXT,
	elr_trans_details_loan_program TEXT,
	elr_trans_details_down_pmt_percent TEXT,
	elr_trans_details_qual_ratio_top TEXT,
	elr_trans_details_qual_ratio_bottom TEXT,
	elr_fannie_mae_loan_doc_type_code TEXT,
	elr_trans_details_purchase_price TEXT,
	elr_trans_details_comb_loan_to_value_cltv TEXT,
	elr_trans_details_apr TEXT,
	elr_trans_details_term_mos TEXT,
	elr_trans_details_interest_only_indicator TEXT,
	elr_prepayment_penalty TEXT,
	elr_mlds_prepymt_penalty_period TEXT,
	elr_trans_details_amort_type TEXT,
	elr_sebonic_custom_impound_field TEXT,
	elr_borrower_first_name TEXT,
	elr_borrower_middle_name TEXT,
	elr_borrower_last_name TEXT,
	elr_borr_email TEXT,
	elr_borr_home_phone TEXT,
	elr_borr_business_phone TEXT,
	elr_borr_cell TEXT,
	elr_borr_present_addr TEXT,
	elr_borr_present_city TEXT,
	elr_borr_present_state TEXT,
	elr_borr_present_zip TEXT,
	elr_borr_dob TEXT,
	elr_borr_sex_male_female TEXT,
	elr_borr_ethnicity TEXT,
	elr_borr_race_american_indian TEXT,
	elr_borr_race_asian TEXT,
	elr_borr_race_black TEXT,
	elr_borr_race_native_hawaiian TEXT,
	elr_borr_race_white TEXT,
	elr_borr_race_info_not_provided TEXT,
	elr_borr_race_not_applicable TEXT,
	elr_borr_first_time_homebuyer TEXT,
	elr_borr_self_employed TEXT,
	elr_income_borr_total_income TEXT,
	elr_financed_property_ownership_count TEXT,
	elr_borr_lmedian_fico TEXT,
	elr_coborr_lmedian_fico TEXT,
	elr_va_loan_summ_credit_score TEXT,
	elr_coborrower_first_name TEXT,
	elr_coborrower_middle_name TEXT,
	elr_coborrower_last_name TEXT,
	elr_coborr_email TEXT,
	elr_coborr_home_phone TEXT,
	elr_coborr_business_phone TEXT,
	elr_coborr_cell TEXT,
	elr_coborr_present_addr TEXT,
	elr_coborr_present_city TEXT,
	elr_coborr_present_state TEXT,
	elr_coborr_present_zip TEXT,
	elr_coborr_dob TEXT,
	elr_coborr_sex_male_female TEXT,
	elr_coborr_experian_fico TEXT,
	elr_coborr_ethnicity TEXT,
	elr_coborr_race_american_indian TEXT,
	elr_coborr_race_asian TEXT,
	elr_coborr_race_black TEXT,
	elr_coborr_race_native_hawaiian TEXT,
	elr_coborr_race_white TEXT,
	elr_coborr_race_info_not_provided TEXT,
	elr_coborr_race_not_applicable TEXT,
	elr_income_verification_available_b1 TEXT,
	elr_income_verification_available_c1 TEXT,
	elr_subject_property_type TEXT,
	elr_subject_property_occupancy_status TEXT,
	elr_subject_property_street TEXT,
	elr_subject_property_street_2 TEXT,
	elr_subject_property_city TEXT,
	elr_subject_property_state TEXT,
	elr_subject_property_zip TEXT,
	elr_subject_property_county TEXT,
	elr_subject_property_msa_number TEXT,
	elr_subject_property_county_code TEXT,
	elr_subject_property_number_units TEXT,
	elr_subject_property_yr_built TEXT,
	elr_subject_property_est_value TEXT,
	elr_subject_property_appraised_value TEXT,
	elr_subject_property_estate_held TEXT,
	elr_occupancy_type TEXT,
	elr_property_type TEXT,
	elr_document_date_received_credit_report TEXT,
	elr_trans_details_credit_rpt_ref_number TEXT,
	elr_payoff_junior_lien_holder_company TEXT,
	elr_payoff_primary_lien_holder_company TEXT,
	elr_appraisal_retrieval_relative_value TEXT,
	elr_appraisal_report_asis TEXT,
	elr_lo_compensation_fee_line_802_discount_point_percent_line_2 TEXT,
	elr_lo_compensation_fee_line_802_discount_point_percent_line_4 TEXT,
	elr_lo_compensation_fee_line_802_user_defined_fee_2_amount TEXT,
	elr_fees_line_801_borr_paid_orig_chrg TEXT,
	elr_fees_line_801_user_defined_fee_2_borr_amt TEXT,
	elr_fees_line_801_broker_compensation_borrower_paid TEXT,
	elr_fees_line_801_user_defined_fee_2_descr TEXT,
	elr_fees_line_802_borr_credit_points TEXT,
	elr_fees_line_803_borr_paid_adj_orig_chrgs TEXT,
	elr_fees_loan_origination_fee_borr TEXT,
	elr_fees_orig_charge_amt_borr TEXT,
	elr_fees_compensation_to_broker_1 TEXT,
	elr_lo_compensation_lender_compensation_credit_amount_line_2 TEXT,
	elr_lo_compensation_borrower_paid_discount_point_amount_line_3 TEXT,
	elr_requested_lo_concession_amount TEXT,
	elr_loan_officer_manager_concession_amount TEXT,
	elr_lo_compensation_borrower_paid_discount_point_amount_line_1 TEXT,
	elr_total_credit_for_rate_chosen TEXT,
	elr_lo_compensation_totalborrower_discount_point_amount_line_4 TEXT,
	elr_hud1_borr_paid_by_for_borr_oth_1_amt TEXT,
	elr_fees_line_801_user_def_fee_1_borr TEXT,
	elr_disclosed_fees_total_finance_charges TEXT,
	elr_document_date_received_loan_officer_preapproval_letter TEXT,
	elr_underwriting_risk_assess_type TEXT,
	elr_underwriting_suspended_date TEXT,
	elr_underwriting_level_of_prpty_review_form_number TEXT,
	elr_uw_suspended_cleared_date TEXT,
	elr_credit_committee_fico_exception TEXT,
	elr_fnma_cu_risk_score TEXT,
	elr_day_1_income_verification_available TEXT,
	elr_du_fail_reason TEXT,
	elr_acceptable_du TEXT,
	elr_acceptable_lp TEXT,
	elr_atr_qm_eligibility_abilitytorepay_loan_type TEXT,
	elr_rate_lock_request_fulfilled_date_time_most_recent TEXT,
	elr_rate_lock_request_fulfilled_date_time TEXT,
	elr_rate_lock_trans_details_loan_program_most_recent TEXT,
	elr_rate_lock_lock_request_loan_type_most_recent TEXT,
	elr_rate_lock_buy_side_base_margin TEXT,
	elr_lock_request_loan_amnt_excluding_mip_pmi_most_recent TEXT,
	elr_lock_request_subject_property_number_units_most_recent TEXT,
	elr_rate_lock_buy_side_lock_expires_date TEXT,
	elr_rate_lock_buy_side_lock_date TEXT,
	elr_first_lock_lock_date TEXT,
	elr_rate_lock_lock_request_impounds_waived_most_recent TEXT,
	elr_rate_lock_lock_request_loan_amount_most_recent TEXT,
	elr_rate_lock_trans_details_amort_type_most_recent TEXT,
	elr_rate_lock_request_rate_sheet_id TEXT,
	elr_rate_lock_buy_side_investor_commitment TEXT,
	elr_rate_lock_buy_side_comments TEXT,
	elr_rate_lock_sell_side_lock_expires_date TEXT,
	elr_rate_lock_sell_side_number_of_days TEXT,
	elr_rate_lock_sell_side_total_sell_price TEXT,
	elr_rate_lock_sell_side_investor_lock_type TEXT,
	elr_rate_lock_sell_investor_name TEXT,
	elr_rate_lock_sell_side_investor_loan_number TEXT,
	elr_rate_lock_sell_side_lock_date TEXT,
	elr_rate_lock_sell_side_lock_date_most_recent TEXT,
	elr_rate_lock_sell_side_base_rate TEXT,
	elr_rate_lock_sell_side_investor_delivery_date TEXT,
	elr_rate_lock_sell_side_base_rate_adjust_1_rate_most_recent TEXT,
	elr_rate_lock_sell_side_investor_commitment_most_recent TEXT,
	elr_rate_lock_sell_side_net_sell_price TEXT,
	elr_rate_lock_sell_side_net_buy_rate TEXT,
	elr_rate_lock_trans_details_term_mos_most_recent TEXT,
	elr_rate_lock_buy_side_number_of_days TEXT,
	elr_first_lock_ltv TEXT,
	elr_first_lock_cltv TEXT,
	elr_first_lock_net_buy_price TEXT,
	elr_trans_details_lock_date TEXT,
	elr_trans_details_rate_lock_expires TEXT,
	elr_trans_details_rate_lock_number_days TEXT,
	elr_lock_extension_original_lock_term TEXT,
	elr_lock_extension_original_lock_date TEXT,
	elr_lock_extension_original_lock_expiration_date TEXT,
	elr_lock_extension_new_expiration_date TEXT,
	elr_initial_capture_of_lock_number_days TEXT,
	elr_trans_details_first_pymt_date TEXT,
	elr_trans_details_first_pymt_adj_date TEXT,
	elr_trans_details_loan_maturity_date TEXT,
	elr_trans_details_total_loan_amt_w_mip_ff TEXT,
	elr_loan_info_arm_disclosure_type TEXT,
	elr_loan_info_arm_margin TEXT,
	elr_freddie_mac_lender_rate_adj_convertible TEXT,
	elr_freddie_mac_loan_to_value_ltv TEXT,
	elr_regz_loan_info_document_date TEXT,
	elr_trans_details_loan_type TEXT,
	elr_trans_details_sub_fin_second_mtg_loan_amt TEXT,
	elr_aus_eligibility_for_miac TEXT,
	elr_total_number_of_borrowers_on_loan TEXT,
	elr_trans_details_mo_pymt_p_and_i TEXT,
	elr_extension_cost_total_amount TEXT,
	elr_homeready_eligibility TEXT,
	elr_homeready_eligibility_review_complete TEXT,
	elr_homeready_borrower_acceptance TEXT,
	elr_homepossible_eligibility TEXT,
	elr_homepossible_eligibility_review_complete TEXT,
	elr_underwriting_investor_eligibility_fannie_mae TEXT,
	elr_underwriting_investor_eligibility_freddie_mac TEXT,
	elr_morgan_stanley_upload TEXT,
	elr_loan_info_arm_first_period_change TEXT,
	elr_loan_info_arm_first_rate_adj_cap TEXT,
	elr_loan_info_arm_floor_rate TEXT,
	elr_loan_info_arm_rate_adj_period TEXT,
	elr_loan_info_arm_rate_cap TEXT,
	elr_loan_info_arm_max_life_interest_cap TEXT,
	elr_mi_company_name_type TEXT,
	elr_file_contacts_mtg_ins_co_name TEXT,
	elr_insurance_mtg_ins_coverage_factor TEXT,
	elr_private_mortgage_insurance_indicator TEXT,
	elr_uldd_mortgage_insurance_premium_source_type TEXT,
	elr_lpmi_estimated_amount_of_lender_paid_mi_premium TEXT,
	elr_lpmi_final_price_of_lpmi TEXT,
	elr_lo_workksheet_mi_premium_frequency TEXT,
	elr_file_contacts_mtg_ins_co_file_number TEXT,
	elr_document_date_received_postfunding_disbursement_ledger TEXT,
	elr_warehouse_curtailment TEXT,
	elr_funding_executed_docs_in_date_time TEXT,
	elr_funding_funds_ordered_date TEXT,
	elr_funding_funds_sent_date TEXT,
	elr_funding_funds_released TEXT,
	elr_fund_outstanding_docs_funding_authorized TEXT,
	elr_delivery_work_completed_checkbox TEXT,
	elr_file_contacts_warehouse_co_name TEXT,
	elr_coll_to_warehouse_warehouse_company TEXT,
	elr_bb_and_t_elds_maturity TEXT,
	elr_intrm_serv_pymnt_summary_prncpl_balance TEXT,
	elr_coll_delivery_dmi_id TEXT,
	elr_intrm_serv_next_pymnt_pymnt_due_date TEXT,
	elr_dmi_upload_p_and_i_change_date TEXT,
	elr_shipping_investor_delivery_date TEXT,
	elr_shipping_actual_shipping_date TEXT,
	elr_coll_delivery_cust_to_inv_ship_date TEXT,
	elr_coll_to_investor_work_completed_date_stamp TEXT,
	elr_coll_delivery_to_custodian_ship_date TEXT,
	elr_purchase_advice_date TEXT,
	elr_purchase_advice_actual_sell_price TEXT,
	elr_purchase_advice_date_first_payment_to_investor TEXT,
	elr_purchase_advice_first_payment_to TEXT,
	elr_purchase_advice_actual_sell_side_srp TEXT,
	elr_purchase_advice_payouts_1_amount TEXT,
	elr_purchase_advice_payouts_2_amount TEXT,
	elr_purchase_advice_payouts_3_amount TEXT,
	elr_purchase_advice_payouts_4_amount TEXT,
	elr_purchase_advice_payouts_5_amount TEXT,
	elr_purchase_advice_payouts_6_amount TEXT,
	elr_purchase_advice_payouts_7_amount TEXT,
	elr_purchase_advice_payouts_8_amount TEXT,
	elr_purchase_advice_payouts_9_amount TEXT,
	elr_purchase_advice_payouts_10_amount TEXT,
	elr_purchase_advice_payouts_11_amount TEXT,
	elr_purchase_advice_payouts_12_amount TEXT,
	elr_purchase_advice_premium TEXT,
	elr_purchase_advice_srp_received TEXT,
	elr_underwriting_investor_eligibility_texas_50a6_cashout TEXT,
	elr_underwriting_investor_eligibility_wells_fargo TEXT,
	elr_underwriting_investor_eligibility_chase_jp_morgan TEXT,
	elr_shipping_mers_registration_date TEXT,
	elr_trans_details_mers_min_number TEXT,
	elr_rate_lock_sell_side_investor_mers_number_most_recent TEXT,
	elr_uldd_pool_id TEXT,
	elr_uldd_property_valuation_effective_date TEXT,
	elr_uldd_first_unit_bedrooms TEXT,
	elr_uldd_first_unit_subject_property_gross_rent TEXT,
	elr_loan_estimate_le_date_issued TEXT,
	elr_appraisal_retrieval_work_completed_date_date TEXT,
	elr_tracking_current_milestone_name TEXT,
	elr_tracking_current_milestone_date TEXT,
	elr_application_milestone_date TEXT,
	elr_trans_details_current_status_date TEXT,
	elr_trans_details_current_loan_status TEXT,
	elr_underwriting_clear_to_close_date TEXT,
	elr_trans_details_est_closing_date TEXT,
	elr_closing_scheduled_date TEXT,
	elr_tracking_doc_signed_milestone_date TEXT,
	elr_cl_docs_delivered_date_stamp TEXT,
	elr_trans_details_total_wire_transfer TEXT,
	elr_trans_details_closed_date TEXT,
	elr_closing_docs_regz_loan_info_disbursement_date TEXT,
	elr_loan_folder_name TEXT,
	elr_file_contacts_buyers_agent_name TEXT,
	elr_file_contacts_buyers_agent_contact_name TEXT,
	elr_file_contacts_buyers_agent_email TEXT,
	elr_file_contacts_loan_officer_name TEXT,
	elr_file_contacts_loan_processor_name TEXT,
	elr_loan_team_member_name_fd_funder TEXT,
	elr_loan_team_member_name_cl_document_fmls TEXT,
	elr_nmls_loan_originator_id TEXT,
	elr_processing_resub_worker_assigned_date_stamp TEXT,
	elr_loan_team_member_name_uw_conditions_fmls TEXT,
	elr_loan_team_member_name_uw_underwriter TEXT,
	elr_loan_officer_appraisal_onhold_estimated_release_date TEXT,
	elr_loan_officer_appraisal_onhold_date_time_stamp TEXT,
	elr_loan_officer_appraisal_cleared_date_time_stamp TEXT,
	elr_refinance_type TEXT,
	elr_trans_details_purchaser_type TEXT,
	elr_trans_details_hoepa_status TEXT,
	elr_loan_info_channel TEXT
);


-- Trigger: set_timestamp_on_encompass_loan_raw_error
CREATE TRIGGER set_timestamp_on_encompass_loan_raw_error
	BEFORE UPDATE
	ON encompass.encompass_loan_raw_error
	FOR EACH ROW
EXECUTE PROCEDURE encompass.set_timestamp();

