name: application
primary_key:
- apl_pid
foreign_keys:
  fk_application_1:
    columns:
    - apl_proposal_pid
    references:
      columns:
      - prp_pid
      schema: staging_octane
      table: proposal
  fkt_apl_address_country:
    columns:
    - apl_address_country
    references:
      columns:
      - code
      schema: staging_octane
      table: country_type
  fkt_apl_fha_borrower_certification_more_than_four_dwellings:
    columns:
    - apl_fha_borrower_certification_more_than_four_dwellings
    references:
      columns:
      - code
      schema: staging_octane
      table: yes_no_unknown_type
  fkt_apl_fha_borrower_certification_own_other_property:
    columns:
    - apl_fha_borrower_certification_own_other_property
    references:
      columns:
      - code
      schema: staging_octane
      table: yes_no_unknown_type
  fkt_apl_fha_borrower_certification_property_to_be_sold:
    columns:
    - apl_fha_borrower_certification_property_to_be_sold
    references:
      columns:
      - code
      schema: staging_octane
      table: yes_no_unknown_type
  fkt_apl_fha_borrower_certification_rental:
    columns:
    - apl_fha_borrower_certification_rental
    references:
      columns:
      - code
      schema: staging_octane
      table: yes_no_unknown_type
  fkt_apl_fha_va_bor_cert_sales_price_exceeds_type:
    columns:
    - apl_fha_va_bor_cert_sales_price_exceeds_type
    references:
      columns:
      - code
      schema: staging_octane
      table: fha_va_bor_cert_sales_price_exceeds_type
  fkt_apl_va_borrower_certification_occupancy_type:
    columns:
    - apl_va_borrower_certification_occupancy_type
    references:
      columns:
      - code
      schema: staging_octane
      table: va_borrower_certification_occupancy_type
columns:
  apl_address_city:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_address_country:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_address_postal_code:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_address_state:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_address_street1:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_address_street2:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_application_name:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_fha_borrower_certification_more_than_four_dwellings:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_fha_borrower_certification_mortgage_amount:
    data_type: NUMERIC(15,0)
    physical_column_flag: true
  apl_fha_borrower_certification_own_other_property:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_fha_borrower_certification_property_to_be_sold:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_fha_borrower_certification_rental:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_fha_borrower_certification_rental_explain:
    data_type: VARCHAR(256)
    physical_column_flag: true
  apl_fha_borrower_certification_sales_price_amount:
    data_type: NUMERIC(15,0)
    physical_column_flag: true
  apl_fha_va_bor_cert_sales_price_exceeds_type:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_pid:
    data_type: BIGINT
    physical_column_flag: true
  apl_primary_application:
    data_type: BOOLEAN
    physical_column_flag: true
  apl_proposal_pid:
    data_type: BIGINT
    physical_column_flag: true
  apl_urla:
    data_type: BOOLEAN
    physical_column_flag: true
  apl_va_borrower_certification_occupancy_type:
    data_type: VARCHAR(128)
    physical_column_flag: true
  apl_version:
    data_type: INTEGER
    physical_column_flag: true
