name: role_config_export_permission
primary_key:
- rcep_pid
foreign_keys:
  fk_role_config_export_permission_1:
    columns:
    - rcep_role_pid
    references:
      columns:
      - r_pid
      schema: staging_octane
      table: role
  fkt_rcep_export_permission_type:
    columns:
    - rcep_config_export_permission_type
    references:
      columns:
      - code
      schema: staging_octane
      table: config_export_permission_type
columns:
  rcep_config_export_permission_type:
    data_type: VARCHAR(128)
    physical_column_flag: true
  rcep_pid:
    data_type: BIGINT
    physical_column_flag: true
  rcep_role_pid:
    data_type: BIGINT
    physical_column_flag: true
  rcep_version:
    data_type: INTEGER
    physical_column_flag: true
