name: secondary_settings
primary_key:
- sset_pid
foreign_keys:
  fk_secondary_settings_1:
    columns:
    - sset_account_pid
    references:
      columns:
      - a_pid
      schema: staging_octane
      table: account
  fk_secondary_settings_2:
    columns:
    - sset_default_lead_source_pid
    references:
      columns:
      - lds_pid
      schema: staging_octane
      table: lead_source
  fk_secondary_settings_3:
    columns:
    - sset_default_mortech_account_pid
    references:
      columns:
      - ma_pid
      schema: staging_octane
      table: mortech_account
  fk_secondary_settings_4:
    columns:
    - sset_default_beneficiary_investor_pid
    references:
      columns:
      - i_pid
      schema: staging_octane
      table: investor
  fk_secondary_settings_5:
    columns:
    - sset_default_servicer_investor_pid
    references:
      columns:
      - i_pid
      schema: staging_octane
      table: investor
columns:
  sset_account_pid:
    data_type: BIGINT
    physical_column_flag: true
  sset_day_ami_uses_subsequent_year:
    data_type: INTEGER
    physical_column_flag: true
  sset_default_beneficiary_investor_pid:
    data_type: BIGINT
    physical_column_flag: true
  sset_default_lead_source_pid:
    data_type: BIGINT
    physical_column_flag: true
  sset_default_mortech_account_pid:
    data_type: BIGINT
    physical_column_flag: true
  sset_default_servicer_investor_pid:
    data_type: BIGINT
    physical_column_flag: true
  sset_disable_all_locking:
    data_type: BOOLEAN
    physical_column_flag: true
  sset_expired_lock_update_allowed_days:
    data_type: INTEGER
    physical_column_flag: true
  sset_high_balance_llpa_filter_applicable_date:
    data_type: DATE
    physical_column_flag: true
  sset_high_balance_llpa_prefixes:
    data_type: VARCHAR(16000)
    physical_column_flag: true
  sset_initial_lender_lock_id:
    data_type: BIGINT
    physical_column_flag: true
  sset_initial_lender_trade_id:
    data_type: BIGINT
    physical_column_flag: true
  sset_lock_expiration_warning_days:
    data_type: INTEGER
    physical_column_flag: true
  sset_min_subordinate_financing_lock_term_days:
    data_type: INTEGER
    physical_column_flag: true
  sset_month_ami_uses_subsequent_year:
    data_type: INTEGER
    physical_column_flag: true
  sset_mortech_disable_eligibility:
    data_type: BOOLEAN
    physical_column_flag: true
  sset_mortech_floating_adjuster_prefixes:
    data_type: VARCHAR(16000)
    physical_column_flag: true
  sset_mortech_strict_eligibility:
    data_type: BOOLEAN
    physical_column_flag: true
  sset_pid:
    data_type: BIGINT
    physical_column_flag: true
  sset_price_match_check_suspend_through_date:
    data_type: DATE
    physical_column_flag: true
  sset_pricing_engine_type:
    data_type: VARCHAR(128)
    physical_column_flag: true
  sset_rate_lock_acknowledgement_due_days:
    data_type: INTEGER
    physical_column_flag: true
  sset_rate_lock_appraisal_inspection_due_days:
    data_type: INTEGER
    physical_column_flag: true
  sset_rate_lock_supporting_documentation_due_days:
    data_type: INTEGER
    physical_column_flag: true
  sset_servicer_loan_id_minimum_available_threshold:
    data_type: INTEGER
    physical_column_flag: true
  sset_servicer_loan_id_minimum_available_warning_email:
    data_type: VARCHAR(256)
    physical_column_flag: true
  sset_third_party_base_margin_prefixes:
    data_type: VARCHAR(16000)
    physical_column_flag: true
  sset_third_party_floating_margin_prefixes:
    data_type: VARCHAR(16000)
    physical_column_flag: true
  sset_version:
    data_type: INTEGER
    physical_column_flag: true
  sset_zillow_appraisal_fee:
    data_type: NUMERIC(15,2)
    physical_column_flag: true
  sset_zillow_recording_fee:
    data_type: NUMERIC(15,2)
    physical_column_flag: true
  sset_zillow_title_fee:
    data_type: NUMERIC(15,2)
    physical_column_flag: true
