name: password_settings
primary_key:
- pws_pid
foreign_keys:
  fk_password_settings_1:
    columns:
    - pws_account_pid
    references:
      columns:
      - a_pid
      schema: staging_octane
      table: account
columns:
  pws_account_pid:
    data_type: BIGINT
  pws_lender_user_expire_days:
    data_type: INTEGER
  pws_lender_user_minimum_change_days:
    data_type: INTEGER
  pws_lender_user_previous_password_ban:
    data_type: INTEGER
  pws_minimum_length:
    data_type: INTEGER
  pws_pid:
    data_type: BIGINT
  pws_require_digit:
    data_type: BOOLEAN
  pws_require_lowercase_letter:
    data_type: BOOLEAN
  pws_require_special_character:
    data_type: BOOLEAN
  pws_require_uppercase_letter:
    data_type: BOOLEAN
  pws_version:
    data_type: INTEGER
