name: config_note
primary_key:
- cn_pid
foreign_keys:
  fk_config_note_1:
    columns:
    - cn_account_pid
    references:
      columns:
      - a_pid
      schema: staging_octane
      table: account
  fk_config_note_2:
    columns:
    - cn_author_lender_user_pid
    references:
      columns:
      - lu_pid
      schema: staging_octane
      table: lender_user
  fk_config_note_3:
    columns:
    - cn_location_pid
    references:
      columns:
      - loc_pid
      schema: staging_octane
      table: location
  fk_config_note_4:
    columns:
    - cn_smart_doc_pid
    references:
      columns:
      - sd_pid
      schema: staging_octane
      table: smart_doc
  fk_config_note_5:
    columns:
    - cn_wf_process_pid
    references:
      columns:
      - wpr_pid
      schema: staging_octane
      table: wf_process
  fk_config_note_6:
    columns:
    - cn_wf_step_pid
    references:
      columns:
      - ws_pid
      schema: staging_octane
      table: wf_step
  fk_config_note_8:
    columns:
    - cn_change_request_pid
    references:
      columns:
      - chr_pid
      schema: staging_octane
      table: change_request
  fkt_cn_config_note_scope_type:
    columns:
    - cn_config_note_scope_type
    references:
      columns:
      - code
      schema: staging_octane
      table: config_note_scope_type
columns:
  cn_account_pid:
    data_type: BIGINT
  cn_author_lender_user_pid:
    data_type: BIGINT
  cn_author_unparsed_name:
    data_type: VARCHAR(128)
  cn_change_request_pid:
    data_type: BIGINT
  cn_config_note_scope_type:
    data_type: VARCHAR(128)
  cn_content:
    data_type: VARCHAR(16000)
  cn_create_datetime:
    data_type: TIMESTAMP
  cn_location_pid:
    data_type: BIGINT
  cn_pid:
    data_type: BIGINT
  cn_scope_name:
    data_type: VARCHAR(1024)
  cn_smart_doc_pid:
    data_type: BIGINT
  cn_version:
    data_type: INTEGER
  cn_wf_process_pid:
    data_type: BIGINT
  cn_wf_step_pid:
    data_type: BIGINT
