name: lender_settings
primary_key:
- lss_pid
foreign_keys:
  fk_lender_settings_1:
    columns:
    - lss_account_pid
    references:
      columns:
      - a_pid
      schema: staging_octane
      table: account
  fk_lender_settings_3:
    columns:
    - lss_hmda_contact_pid
    references:
      columns:
      - lu_pid
      schema: staging_octane
      table: lender_user
  fk_lender_settings_4:
    columns:
    - lss_default_standalone_lock_term_setting_pid
    references:
      columns:
      - lts_pid
      schema: staging_octane
      table: lock_term_setting
  fk_lender_settings_5:
    columns:
    - lss_default_combo_lock_term_setting_pid
    references:
      columns:
      - lts_pid
      schema: staging_octane
      table: lock_term_setting
  fk_lender_settings_6:
    columns:
    - lss_fha_home_office_location_pid
    references:
      columns:
      - loc_pid
      schema: staging_octane
      table: location
  fkt_lss_borrower_quote_filter_pivot_type:
    columns:
    - lss_borrower_quote_filter_pivot_type
    references:
      columns:
      - code
      schema: staging_octane
      table: quote_filter_pivot_type
  fkt_lss_company_time_zone_type:
    columns:
    - lss_company_time_zone_type
    references:
      columns:
      - code
      schema: staging_octane
      table: time_zone_type
  fkt_lss_default_credit_bureau_type:
    columns:
    - lss_default_credit_bureau_type
    references:
      columns:
      - code
      schema: staging_octane
      table: credit_bureau_type
  fkt_lss_fha_sponsor_address_country:
    columns:
    - lss_fha_sponsor_address_country
    references:
      columns:
      - code
      schema: staging_octane
      table: country_type
  fkt_lss_hmda_agency_id_type:
    columns:
    - lss_hmda_agency_id_type
    references:
      columns:
      - code
      schema: staging_octane
      table: hmda_agency_id_type
  fkt_lss_lp_submission_type:
    columns:
    - lss_lp_submission_type
    references:
      columns:
      - code
      schema: staging_octane
      table: lp_submission_type
  fkt_lss_preferred_aus_type:
    columns:
    - lss_preferred_aus_type
    references:
      columns:
      - code
      schema: staging_octane
      table: aus_type
columns:
  lss_pid:
    data_type: BIGINT
  lss_version:
    data_type: INTEGER
  lss_account_pid:
    data_type: BIGINT
  lss_company_time_zone_type:
    data_type: VARCHAR(128)
  lss_va_lender_id:
    data_type: VARCHAR(16)
  lss_usda_lender_id:
    data_type: VARCHAR(16)
  lss_fha_lender_id:
    data_type: VARCHAR(16)
  lss_fha_home_office_branch_pid:
    data_type: BIGINT
  lss_fha_sponsor_id:
    data_type: VARCHAR(16)
  lss_fha_sponsor_company_name:
    data_type: VARCHAR(32)
  lss_fha_sponsor_address_street1:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_street2:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_city:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_state:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_postal_code:
    data_type: VARCHAR(128)
  lss_fha_sponsor_address_country:
    data_type: VARCHAR(128)
  lss_fha_non_supervised_mortgagee:
    data_type: BOOLEAN
  lss_fnma_seller_id:
    data_type: VARCHAR(16)
  lss_fre_seller_id:
    data_type: VARCHAR(16)
  lss_lp_submission_type:
    data_type: VARCHAR(128)
  lss_lender_user_email_from:
    data_type: VARCHAR(256)
  lss_hmda_contact_pid:
    data_type: BIGINT
  lss_hmda_legal_entity_id:
    data_type: VARCHAR(20)
  lss_hmda_respondent_id:
    data_type: VARCHAR(32)
  lss_hmda_agency_id_type:
    data_type: VARCHAR(128)
  lss_prequalification_program:
    data_type: BOOLEAN
  lss_preapproval_program:
    data_type: BOOLEAN
  lss_pest_inspector_company_name:
    data_type: VARCHAR(128)
  lss_pest_inspector_phone:
    data_type: VARCHAR(32)
  lss_pest_inspector_website_url:
    data_type: VARCHAR(256)
  lss_pest_inspector_address_street1:
    data_type: VARCHAR(128)
  lss_pest_inspector_address_street2:
    data_type: VARCHAR(128)
  lss_pest_inspector_address_city:
    data_type: VARCHAR(128)
  lss_pest_inspector_address_state:
    data_type: VARCHAR(128)
  lss_pest_inspector_address_postal_code:
    data_type: VARCHAR(128)
  lss_take_application_hours:
    data_type: VARCHAR(128)
  lss_originator_title:
    data_type: VARCHAR(128)
  lss_default_credit_bureau_type:
    data_type: VARCHAR(128)
  lss_sap_minimum_decision_credit_score:
    data_type: INTEGER
  lss_default_standalone_lock_term_setting_pid:
    data_type: BIGINT
  lss_default_combo_lock_term_setting_pid:
    data_type: BIGINT
  lss_preferred_aus_type:
    data_type: VARCHAR(128)
  lss_borrower_quote_filter_pivot_type:
    data_type: VARCHAR(128)
  lss_borrower_quote_filter_pivot_lower_count:
    data_type: INTEGER
  lss_borrower_quote_filter_pivot_higher_count:
    data_type: INTEGER
  lss_fha_home_office_location_pid:
    data_type: BIGINT
