-- new schema: test
GRANT USAGE ON SCHEMA test TO readonly;
GRANT USAGE ON SCHEMA test TO mditest;

GRANT SELECT ON ALL TABLES IN SCHEMA test TO readonly;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA test TO mditest;
