
----------------------------------------
-- This script is an addendum to the full script generated by staging_history_metadata_creater.sql
-- This will update the source_edw_field_definition_dwid in the history_octane field definitions.
--
-- WARNING: This is designed to work when there are no other joins declared from the tables other than the join from
-- staging_octane to history_octane.
----------------------------------------

update mdi.edw_field_definition --history_field
SET source_edw_field_definition_dwid  = staging_field.dwid
FROM mdi.edw_table_definition as history_table
JOIN mdi.edw_table_definition as staging_table on history_table.table_name = staging_table.table_name and staging_table.schema_name = 'staging_octane'
JOIN mdi.edw_field_definition as staging_field ON staging_field.edw_table_definition_dwid = staging_table.dwid
where staging_field.field_name = edw_field_definition.field_name
 AND edw_field_definition.edw_table_definition_dwid = history_table.dwid
 and history_table.schema_name = 'history_octane'
;
