name: application_dim
primary_source_table: staging.history_octane.application
primary_key:
- dwid
columns:
  dwid:
    data_type: BIGINT
    update_flag: false
  data_source_dwid:
    data_type: BIGINT
    update_flag: true
  edw_created_datetime:
    data_type: TIMESTAMPTZ
    update_flag: false
  edw_modified_datetime:
    data_type: TIMESTAMPTZ
    update_flag: true
  etl_batch_id:
    data_type: TEXT
    update_flag: true
  data_source_integration_columns:
    data_type: TEXT
    update_flag: true
  data_source_integration_id:
    data_type: TEXT
    update_flag: false
  data_source_modified_datetime:
    data_type: TIMESTAMPTZ
    update_flag: false
  application_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.apl_pid
    update_flag: true
  proposal_pid:
    data_type: BIGINT
    source:
      field: primary_source_table.columns.apl_proposal_pid
    update_flag: true
etls:
  SP-200003:
    input_type: table
    output_type: insert_update
    hardcoded_data_source: Octane
    json_output_field: data_source_integration_id
    insert_update_keys:
      - data_source_integration_id
    container_memory: 2048
    input_sql: |-
      WITH application_dim_incl_new_records AS (
          SELECT 'application_pid' || '~' || 'data_source_dwid' AS data_source_integration_columns
               , COALESCE( CAST( primary_table.apl_pid AS TEXT ), '<NULL>' ) || '~' ||
                 COALESCE( CAST( 1 AS TEXT ), '<NULL>' ) AS data_source_integration_id
               , NOW( ) AS edw_created_datetime
               , NOW( ) AS edw_modified_datetime
               , primary_table.data_source_updated_datetime AS data_source_modified_datetime
               , primary_table.apl_pid AS application_pid
               , primary_table.apl_proposal_pid AS proposal_pid
               , GREATEST( primary_table.etl_end_date_time ) AS max_source_etl_end_date_time
          FROM (
              SELECT <<application_partial_load_condition>> AS include_record
                   , application.*
                   , etl_log.etl_end_date_time
              FROM history_octane.application
              LEFT JOIN history_octane.application AS history_records
                        ON application.apl_pid = history_records.apl_pid
                            AND application.data_source_updated_datetime < history_records.data_source_updated_datetime
              JOIN star_common.etl_log
                   ON application.etl_batch_id = etl_log.etl_batch_id
              WHERE history_records.apl_pid IS NULL
          ) AS primary_table
          WHERE GREATEST( primary_table.include_record ) IS TRUE
      )
      --new records that should be inserted
      SELECT application_dim_incl_new_records.*
      FROM application_dim_incl_new_records
      LEFT JOIN star_loan.application_dim
                ON application_dim_incl_new_records.data_source_integration_id = application_dim.data_source_integration_id
      WHERE application_dim.dwid IS NULL
      UNION ALL
      --existing records that need to be updated
      SELECT application_dim_incl_new_records.*
      FROM application_dim_incl_new_records
      JOIN (
          SELECT application_dim.data_source_integration_id, etl_log.etl_start_date_time
          FROM star_loan.application_dim
          JOIN star_common.etl_log
               ON application_dim.etl_batch_id = etl_log.etl_batch_id
      ) AS application_dim_etl_start_times
           ON application_dim_incl_new_records.data_source_integration_id = application_dim_etl_start_times.data_source_integration_id
               AND application_dim_incl_new_records.max_source_etl_end_date_time >= application_dim_etl_start_times.etl_start_date_time;
next_etls:
- SP-300001-insert-update
