--
-- EDW | star_loan schema: Add indexes to tables' key lookup fields
-- https://app.asana.com/0/0/1200975391827399
--

CREATE INDEX application_dim_data_source_integration_id ON star_loan.application_dim USING btree(data_source_integration_id);
CREATE INDEX borrower_demographics_dim_data_source_integration_id ON star_loan.borrower_demographics_dim USING btree(data_source_integration_id);
CREATE INDEX borrower_dim_data_source_integration_id ON star_loan.borrower_dim USING btree(data_source_integration_id);
CREATE INDEX borrower_lending_profile_dim_data_source_integration_id ON star_loan.borrower_lending_profile_dim USING btree(data_source_integration_id);
CREATE INDEX hmda_purchaser_of_loan_dim_data_source_integration_id ON star_loan.hmda_purchaser_of_loan_dim USING btree(data_source_integration_id);
CREATE INDEX interim_funder_dim_data_source_integration_id ON star_loan.interim_funder_dim USING btree(data_source_integration_id);
CREATE INDEX investor_dim_data_source_integration_id ON star_loan.investor_dim USING btree(data_source_integration_id);
CREATE INDEX lender_user_dim_data_source_integration_id ON star_loan.lender_user_dim USING btree(data_source_integration_id);
CREATE INDEX loan_beneficiary_dim_data_source_integration_id ON star_loan.loan_beneficiary_dim USING btree(data_source_integration_id);
CREATE INDEX loan_dim_data_source_integration_id ON star_loan.loan_dim USING btree(data_source_integration_id);
CREATE INDEX loan_fact_data_source_integration_id ON star_loan.loan_fact USING btree(data_source_integration_id);
CREATE INDEX loan_funding_dim_data_source_integration_id ON star_loan.loan_funding_dim USING btree(data_source_integration_id);
CREATE INDEX loan_junk_dim_data_source_integration_id ON star_loan.loan_junk_dim USING btree(data_source_integration_id);
CREATE INDEX mortgage_insurance_dim_data_source_integration_id ON star_loan.mortgage_insurance_dim USING btree(data_source_integration_id);
CREATE INDEX product_choice_dim_data_source_integration_id ON star_loan.product_choice_dim USING btree(data_source_integration_id);
CREATE INDEX product_dim_data_source_integration_id ON star_loan.product_dim USING btree(data_source_integration_id);
CREATE INDEX product_terms_dim_data_source_integration_id ON star_loan.product_terms_dim USING btree(data_source_integration_id);
CREATE INDEX transaction_dim_data_source_integration_id ON star_loan.transaction_dim USING btree(data_source_integration_id);
CREATE INDEX transaction_junk_dim_data_source_integration_id ON star_loan.transaction_junk_dim USING btree(data_source_integration_id);
